#ifndef __SHARED_CASTLESIEGE_H__
#define __SHARED_CASTLESIEGE_H__

#pragma once

enum WEAPON_STATE
{
	WEAPON_STATE_NORMAL = 0x00,
	WEAPON_STATE_USABLE = 0x01,
	WEAPON_STATE_USING = 0x02,
};

enum WEAPON_TYPE
{
	WEAPON_TYPE_CASTLE_ATTACKER = 0x01,
	WEAPON_TYPE_CASTLE_DEFENDER = 0x02,
	WEAPON_TYPE_CASTLE_GUARDIAN = 0x03,
};

enum WEAPON_USE_RESULT
{
	WEAPON_USE_FAIL = 0x00,
	WEAPON_USE_SUCCESS = 0x01,
};

enum CASTLE_HUNTZONE_NPCTALK_RESULT
{
	CASTLE_HUNTZONE_ENTRANCE_DISABLE			= 0x00,
	CASTLE_HUNTZONE_ENTRANCE_ENABLE				= 0x01,
	CASTLE_HUNTZONE_ENTRANCE_ENABLE_TO_MEMBER	= 0x02,
	CASTLE_HUNTZONE_ENTRANCE_ENABLE_TO_OWNER	= 0x03,
};

enum CASTLE_HUNTZONE_SETTING
{
	CASTLE_HUNTZONE_SETTING_FAIL				= 0x00,	
	CASTLE_HUNTZONE_SETTING_SUCCESS				= 0x01,
};

enum CASTLE_HUNTZONE_USAGE
{
	CASTLE_HUNTZONE_USAGE_DISABLE				= 0x00,	
	CASTLE_HUNTZONE_USAGE_ENABLE				= 0x01,
};

#endif