#ifndef __SHARED_ENCRYPTION_H__
#define __SHARED_ENCRYPTION_H__

#pragma once

#include <mu_blowfish.h>

// Client<->Server
#define CTS_ENCRYPTION_BLOCKSIZE MUBlowfish::BytesLength
#define CTS_ENCRYPTION_KEYSIZE MUBlowfish::KeyLength

// Server<->Server
#define STS_ENCRYPTION_BLOCKSIZE MUBlowfish::BytesLength
#define STS_ENCRYPTION_KEYSIZE MUBlowfish::KeyLength

#define NET_ENCRYPTION_KEYSIZE (CTS_ENCRYPTION_KEYSIZE > STS_ENCRYPTION_KEYSIZE ? CTS_ENCRYPTION_KEYSIZE : STS_ENCRYPTION_KEYSIZE)
#define NET_ENCRYPTION_BLOCKSIZE (CTS_ENCRYPTION_BLOCKSIZE > STS_ENCRYPTION_BLOCKSIZE ? CTS_ENCRYPTION_BLOCKSIZE : STS_ENCRYPTION_BLOCKSIZE)

#endif