#ifndef __SHARED_MIX_H__
#define __SHARED_MIX_H__

#pragma once

enum CHAOS_TYPE
{
	CHAOS_TYPE_DEFAULT = 1,
	CHAOS_TYPE_DEVILSQUARE = 2,
	CHAOS_TYPE_UPGRADE_10 = 3,
	CHAOS_TYPE_UPGRADE_11 = 4,
	CHAOS_TYPE_UPGRADE_12 = 22,
	CHAOS_TYPE_UPGRADE_13 = 23,
	CHAOS_TYPE_UPGRADE_14 = 49,
	CHAOS_TYPE_UPGRADE_15 = 50,
	CHAOS_TYPE_DINORANT = 5,
	CHAOS_TYPE_FRUIT = 6,
	CHAOS_TYPE_SECOND_WING = 7,
	CHAOS_TYPE_BLOODCATLE = 8,
	CHAOS_TYPE_FIRST_WING = 11,
	CHAOS_TYPE_SETITEM = 12,
	CHAOS_TYPE_DARKHORSE = 13,
	CHAOS_TYPE_DARKSPIRIT = 14,
	CHAOS_TYPE_CLOAK = 24,

	CHAOS_TYPE_BLESS_POTION = 15,
	CHAOS_TYPE_SOUL_POTION = 16,
	CHAOS_TYPE_LIFE_STONE = 17,

	CHAOS_TYPE_CASTLE_ITEM = 18,

	CHAOS_TYPE_HT_BOX = 20,

	CHAOS_TYPE_FENRIR_01 = 25,
	CHAOS_TYPE_FENRIR_02 = 26,
	CHAOS_TYPE_FENRIR_03 = 27,
	CHAOS_TYPE_FENRIR_04 = 28,

	CHAOS_TYPE_COMPOUNDPOTION_LV1 = 30,
	CHAOS_TYPE_COMPOUNTPOTION_LV2 = 31,
	CHAOS_TYPE_COMPOUNTPOTION_LV3 = 32,

	CHAOS_TYPE_JEWELOFHARMONY_PURITY = 33,
	CHAOS_TYPE_JEWELOFHARMONY_MIX_SMELTINGITEM = 34,
	CHAOS_TYPE_JEWELOFHARMONY_RESTORE_ITEM = 35,

	CHAOS_TYPE_380_OPTIONITEM = 36,
	CHAOS_TYPE_ILLUSION_TEMPLE_ITEM = 37,
	CHAOS_TYPE_THIRD_WING_1 = 38,
	CHAOS_TYPE_THIRD_WING_2 = 39,
	CHAOS_TYPE_LOTTERY_MIX = 40,
	CHAOS_TYPE_CHERRY_MIX = 41,
	CHAOS_TYPE_SEED_EXTRACT = 42,
	CHAOS_TYPE_SEED_COMPOSIT = 43,
	CHAOS_TYPE_SEED_EQUIP = 44,
	CHAOS_TYPE_SEED_REMOVE = 45,
	CHAOS_TYPE_DUNGEON_KEYITEM = 46,
	CHAOS_TYPE_GOLD_AND_SILBER_BOX = 47,
};

#endif