#ifndef __MU_DEFINE_H__
#define __MU_DEFINE_H__

#pragma once

#if !defined(NDEBUG) && DIRECTX_BACKEND_ENABLE == 1
#define DEBUG_REPORT
#endif

#define TERRAIN_SIZE 256
#define TERRAIN_SIZE_MASK 255
#define MAX_TERRAIN_SIZE (TERRAIN_SIZE * TERRAIN_SIZE)
static constexpr mu_float g_TerrainScale = 100.0f;
static constexpr mu_float g_TerrainScaleRev = 0.01f;
static const EVector3 g_TerrainScaleRev3 = EVector3(g_TerrainScaleRev, g_TerrainScaleRev, 1.0f);
static const EVector4 g_TerrainScaleRev4 = EVector4(g_TerrainScaleRev, g_TerrainScaleRev, 1.0f, 1.0f);

#define GAME_TIME (25.0)
#define GAME_FPS (1000.0 / GAME_TIME)
#define GAME_FPS64 (1000000.0 / GAME_TIME)

#define MAX_TASKING_THREADS 8
#define MAX_BONES 200
#define MAX_MESH 50
#define MAX_VERTICES 15000

#define INVALID_PARTICLE 0xFFFFFFFF

#define TEMP_CHARACTERS_INDEX 300
#define MAX_CHARACTERS_CLIENT 400
#define MAX_VIEWPORT MAX_CHARACTERS_CLIENT // How many players, monsters and npcs will be displayed

#define MAX_KEYS 30000

#define MAX_OBJECTS 10000
#define MAX_BUTTERFLES 1100
#define MAX_BOIDS 40
#define MAX_FISHS 10
#define MAX_PETS 400
#define MAX_EFFECTS 1000
#define MAX_EFFECTS_WAIT MAX_EFFECTS
#define MAX_SPRITES 5000
#define MAX_TILESPRITES 1000
#define MAX_PARTICLES 4000
#define MAX_PARTICLES_WAIT MAX_PARTICLES // Particles what wait to be created what come from locked particles processing(Move, Render, etc...)
#define MAX_JOINTS 1000
#define MAX_JOINTS_WAIT MAX_JOINTS
#define MAX_TAILS  50
#define MAX_LEAVES 200
#define MAX_LEAVES_DOUBLE 400
#define MAX_POINTERS 200
#define MAX_POINTS 200
#define MAX_GUILDSPRITES (MAX_CHARACTERS_CLIENT + 300)

#define MAX_BLURS				100
#define MAX_BLUR_TAILS			30
#define MAX_BLUR_LIFETIME		30

#define MAX_OBJECTBLURS			200
#define MAX_OBJECTBLUR_TAILS	100
#define MAX_OBJECTBLUR_LIFETIME 30

#define MAX_MODEL_MONSTER	400

#define NUMOFMON 10000

#define MAX_PATH_FIND	50

#define TW_SAFEZONE		( 0x0001)
#define TW_CHARACTER	( 0x0002)
#define TW_NOMOVE		( 0x0004)
#define TW_NOGROUND		( 0x0008)
#define TW_WATER		( 0x0010)
#define TW_ACTION       ( 0x0020)
#define TW_HEIGHT       ( 0x0040)
#define TW_CAMERA_UP    ( 0x0080)
#define TW_NOATTACKZONE ( 0x0100)
#define TW_ATT1         ( 0x0200)
#define TW_ATT2         ( 0x0400)
#define TW_ATT3         ( 0x0800)
#define TW_ATT4         ( 0x1000)
#define TW_ATT5         ( 0x2000)
#define TW_ATT6         ( 0x4000)
#define TW_ATT7         ( 0x8000)

#define FACTOR_PATH_DIST		( 5)
#define FACTOR_PATH_DIST_DIAG	( ( mu_int32)( ( mu_float)FACTOR_PATH_DIST * 1.414f))

#define MAX_COUNT_PATH		(500)
#define MAX_INT_FORPATH		(65000 * 30000)

#define PATH_INTESTLIST		( 0x01)
#define PATH_TESTED			( 0x02)
#define PATH_END			( 0x04)

#define MAX_GUILDNAME_SIZE	8
#define MAX_TEXT_LENGTH		255

#define MAX_GATES           512
#define MAX_DIALOG			200

#define MAX_ITEM_TYPE      16
#define MAX_ITEM_INDEX     512
#define MAX_ITEM           (MAX_ITEM_TYPE*MAX_ITEM_INDEX)

#define	MAX_MASTER		   24
#define MAX_ITEM_SPECIAL   8
#define ITEM_LEVEL_NORMAL  4
#define MAX_QUEST_ITEM     64
#define MAX_EVENT_ITEM     35

#define MAX_ITEM_LEVEL		(15)

#define MAX_SOCKETS			5
#define SOCKET_EMPTY		0xFF

#define TRADE_BUY    0
#define TRADE_SELL   1
#define TRADE_REPAIR 2

#define CHAOS_MIX_LEVEL 10

#define MOVEMENT_MOVE    0
#define MOVEMENT_TALK    2
#define MOVEMENT_OPERATE 4
#define MOVEMENT_SKILL	 5

#define INVENTORY_SCALE        20

#define COLUMN_INVENTORY       8
#define ROW_INVENTORY          8

#define COLUMN_STORAGE         8
#define ROW_STORAGE            15

#define COLUMN_SHOP_INVENTORY  8
#define ROW_SHOP_INVENTORY     15

#define COLUMN_TRADE_INVENTORY 8
#define ROW_TRADE_INVENTORY    4

#define COLUMN_MIX_INVENTORY   8
#define ROW_MIX_INVENTORY      4

#define MAX_INVENTORY          (COLUMN_INVENTORY*ROW_INVENTORY)
#define MAX_STORAGE            (COLUMN_STORAGE*ROW_STORAGE)
#define MAX_SHOP_INVENTORY     (COLUMN_SHOP_INVENTORY*ROW_SHOP_INVENTORY)
#define MAX_TRADE_INVENTORY    (COLUMN_TRADE_INVENTORY*ROW_TRADE_INVENTORY)
#define MAX_MIX_INVENTORY      (COLUMN_MIX_INVENTORY*ROW_MIX_INVENTORY)

#define REQUEST_EQUIPMENT_INVENTORY 0
#define REQUEST_EQUIPMENT_TRADE 1
#define REQUEST_EQUIPMENT_STORAGE 2
#define REQUEST_EQUIPMENT_CHAOS_MIX 3
#define REQUEST_EQUIPMENT_MYSHOP 4
#define REQUEST_EQUIPMENT_TRAINER_MIX 5
#define REQUEST_EQUIPMENT_ELPIS_MIX 6
#define REQUEST_EQUIPMENT_OSBOURNE_MIX 7
#define REQUEST_EQUIPMENT_JERRIDON_MIX 8
#define REQUEST_EQUIPMENT_CHAOS_CARD_MIX 9
#define REQUEST_EQUIPMENT_CHERRYBLOSSOM_MIX 10
#define REQUEST_EQUIPMENT_EXTRACT_SEED_MIX 11
#define REQUEST_EQUIPMENT_SEED_SPHERE_MIX 12
#define REQUEST_EQUIPMENT_ATTACH_SOCKET_MIX 13
#define REQUEST_EQUIPMENT_DETACH_SOCKET_MIX 14

#define MAX_EQUIPMENT_INDEX			GAME::MAX_EQUIPMENT
#define MAX_MY_INVENTORY_INDEX		MAX_EQUIPMENT_INDEX + MAX_INVENTORY

#define MODEL_BODY_NUM              20
#define MODEL_ITEM_COMMON_NUM		2

#define MAX_SETITEM_OPTIONS			12

#define MAX_SHOPTITLE 36
#define COL_PERSONALSHOP_INVEN 8
#define ROW_PERSONALSHOP_INVEN 4
#define MAX_PERSONALSHOP_INVEN COL_PERSONALSHOP_INVEN*ROW_PERSONALSHOP_INVEN

#define MAX_ITEMS 1000

enum
{
	ITEM_SWORD		= 0,
	ITEM_AXE		= (1 * MAX_ITEM_INDEX),
	ITEM_MACE		= (2 * MAX_ITEM_INDEX),
	ITEM_SPEAR		= (3 * MAX_ITEM_INDEX),
	ITEM_BOW		= (4 * MAX_ITEM_INDEX),
	ITEM_STAFF		= (5 * MAX_ITEM_INDEX),
	ITEM_SHIELD		= (6 * MAX_ITEM_INDEX),
	ITEM_HELM		= (7 * MAX_ITEM_INDEX),
	ITEM_ARMOR		= (8 * MAX_ITEM_INDEX),
	ITEM_PANTS		= (9 * MAX_ITEM_INDEX),
	ITEM_GLOVES		= (10 * MAX_ITEM_INDEX),
	ITEM_BOOTS		= (11 * MAX_ITEM_INDEX),
	ITEM_WING		= (12 * MAX_ITEM_INDEX),
	ITEM_HELPER		= (13 * MAX_ITEM_INDEX),
	ITEM_POTION		= (14 * MAX_ITEM_INDEX),
	ITEM_ETC		= (15 * MAX_ITEM_INDEX),
};

enum
{
	PARTS_NONE = 0,
	PARTS_START,
	PARTS_STAFF = PARTS_START,
	PARTS_SWORD,
	PARTS_BOW,
	PARTS_LION = 4,
	PARTS_ATTACK_TEAM_MARK,
	PARTS_ATTACK_TEAM_MARK2,
	PARTS_ATTACK_TEAM_MARK3,
	PARTS_ATTACK_KING_TEAM_MARK,
	PARTS_ATTACK_KING_TEAM_MARK2,
	PARTS_ATTACK_KING_TEAM_MARK3,
	PARTS_DEFENSE_TEAM_MARK,
	PARTS_DEFENSE_KING_TEAM_MARK,
	PARTS_END
};

#define ABILITY_FAST_ATTACK_SPEED	( 0x01)
#define ABILITY_PLUS_DAMAGE			( 0x02)
#define ABILITY_FAST_ATTACK_RING	( 0x04)
#define ABILITY_FAST_ATTACK_SPEED2	( 0x08)

#define CTLCODE_01BLOCKCHAR			(1 << 0)
#define CTLCODE_02BLOCKITEM			(1 << 2)
#define CTLCODE_10ACCOUNT_BLOCKITEM	(1 << 3)
#define CTLCODE_EVENT_GM			(1 << 4)
#define CTLCODE_ADMIN				(1 << 5)

#define INDEX_COMPILED_CELE		ITEM_WING+30
#define INDEX_COMPILED_SOUL		ITEM_WING+31
#define MODEL_COMPILED_CELE		MODEL_WING+30
#define MODEL_COMPILED_SOUL		MODEL_WING+31
#define MAX_LINE_UNMIXLIST		8

#define INDEX_NPC_LAHAP			9
#define MAX_BUFF_SLOT_INDEX     16

#define ITEM_TYPE_CHARM_MIXWING		ITEM_HELPER
#define MODEL_TYPE_CHARM_MIXWING	MODEL_HELPER

enum E_WINGMIXCHAR_SEQUENCE
{
	EWS_KNIGHT_1_CHARM = 83,
	EWS_MAGICIAN_1_CHARM,
	EWS_ELF_1_CHARM,
	EWS_SUMMONER_1_CHARM,
	EWS_DARKLORD_1_CHARM,
	EWS_KNIGHT_2_CHARM,
	EWS_MAGICIAN_2_CHARM,
	EWS_ELF_2_CHARM,
	EWS_SUMMONER_2_CHARM,
	EWS_DARKKNIGHT_2_CHARM,
	EWS_BEGIN = 83,
	EWS_END = EWS_BEGIN + 10,
};

enum
{
	STARTUP_SCENE,
	LOG_IN_SCENE,
	CHARACTER_SCENE,
	WAITING_SCENE,
	MAIN_SCENE,
};

#define MAX_FENRIR_SKILL_MONSTER_NUM	10
#define FENRIR_TYPE_BLACK	0
#define FENRIR_TYPE_RED		1
#define FENRIR_TYPE_BLUE	2
#define FENRIR_TYPE_GOLD	3

#define MAX_BLOOD_CASTLE_MEN    10
#define MAX_CHAOS_CASTLE_MEN    100

#define BATTLE_CASTLE_WALL1 61
#define BATTLE_CASTLE_WALL2 62
#define BATTLE_CASTLE_WALL3 63
#define BATTLE_CASTLE_WALL4 64

#define DREADFEAR_ATTACK2_MOTION_COUNT 2

#define KANTURU2ND_STATETEXT_MAX	3
#define KANTURU2ND_REFRESH_GAPTIME	2000
#define KANTURU2ND_REFRESHBUTTON_GAPTIME 1000

#define KANTURU2ND_NPC_ANI_STOP	0
#define KANTURU2ND_NPC_ANI_ROT	1

#define WATER_TERRAIN_SIZE      256
#define MAX_WATER_SIZE          4
#define MAX_WATER_GRID          80
#define VIEW_WATER_GRID         100
#define WAVE_SCALE              50.0f

#define BLOODCASTLE_NUM 8
#define HELLAS_NUM      7
#define CHAOS_NUM       6

#define TERRAIN_MAP_NORMAL 0
#define TERRAIN_MAP_ALPHA  1
#define TERRAIN_MAP_GRASS  2
#define TERRAIN_MAP_TRAP   3

enum eITEM_TYPE
{
	IT_NONE,
	IT_HELM,
	IT_ARMOR,
	IT_PANTS,
	IT_GLOVES,
	IT_BOOTS,
	IT_RING,
	IT_NECKLACE,
	IT_WINGS,
	IT_PET,
	IT_HELPER,
	IT_SWORD,
	IT_AXE,
	IT_MACE,
	IT_SPEAR,
	IT_STAFF,
	IT_STICK,
	IT_BOOK,
	IT_BOW,
	IT_CROSSBOW,
	IT_SHIELD,
	IT_ARROW,
	IT_BOLTS,
	IT_SCROLL,
	IT_POTIONS,
	IT_JEWELS,
	IT_QUEST,
};

#define MAX_RESISTANCE		7
#define MAX_MONSTER			1024
#define MAX_SKILLS			600

#define MAX_DUTY_CLASS		3

enum SET_OPTION_TYPE
{
	SET_OPTION_NONE = 0,
	SET_OPTION_STRENGTH,
	SET_OPTION_DEXTERITY,
	SET_OPTION_ENERGY,
	SET_OPTION_VITALITY,
};

enum EXCELLENT_OPTION_TYPE
{
	EXCELLENT_NONE = 0,
};

#define BODYPART_HEAD   0
#define BODYPART_HELM   1
#define BODYPART_ARMOR  2
#define BODYPART_PANTS  3
#define BODYPART_GLOVES 4
#define BODYPART_BOOTS  5
#define MAX_BODYPART    6

#define PVP_HERO2		1
#define PVP_HERO1		2
#define PVP_NEUTRAL		3
#define PVP_CAUTION		4
#define PVP_MURDERER1	5
#define PVP_MURDERER2	6

#define RESISTANCE_COLD				0
#define RESISTANCE_POISON			1
#define RESISTANCE_THUNDER			2
#define RESISTANCE_FIRE				3
#define RESISTANCE_EARTH            4
#define RESISTANCE_WIND             5
#define RESISTANCE_WATER            6

enum
{
	PET_FLYING = 0,
	PET_FLY,
	PET_ESCAPE,
	PET_STAND,
	PET_STAND_START,
	PET_ATTACK,
	PET_ATTACK_MAGIC,
	PET_END,
};

enum PET_TYPE
{
	PET_TYPE_NONE = -1,
	PET_TYPE_DARK_SPIRIT = 0,
	PET_TYPE_DARK_HORSE,
	PET_TYPE_END,
};

enum PET_COMMAND
{
	PET_CMD_DEFAULT = 0,
	PET_CMD_RANDOM,
	PET_CMD_OWNER,
	PET_CMD_TARGET,
	PET_CMD_END,
};

#define MAX_GUILD_LINE   14
#define MAX_GUILDS       80

#define MAX_MARKS   (2000)

namespace SERVERLIST
{
	enum
	{
		LEFT_GROUP_COUNT = 10,
		RIGHT_GROUP_COUNT = 10,
		CENTER_GROUP_COUNT = 1,

		LEFT_GROUP_INDEX = 0,
		RIGHT_GROUP_INDEX = LEFT_GROUP_COUNT,
		CENTER_GROUP_INDEX = LEFT_GROUP_COUNT + RIGHT_GROUP_COUNT,

		MAX_SERVER_GROUP = LEFT_GROUP_COUNT + RIGHT_GROUP_COUNT + CENTER_GROUP_COUNT,
		MAX_SERVER = 16,
	};
}

#endif