#ifndef __MU_DATALIST_H__
#define __MU_DATALIST_H__

#pragma once

namespace GAMEDATA
{
	enum : mu_uint32
	{
		TEXT_DATA,
		FILTER_DATA,
		FILTERNAME_DATA,
		DIALOG_DATA,
		MOVEREQ_DATA,
		GATE_DATA,
		BUFFEFFECT_DATA,
		ITEM_DATA,
		ITEMCATEGORIES_DATA,
		ITEMADDOPTION_DATA,
		ITEMSETOPTION_DATA,
		SOCKETITEM_DATA,
		SKILL_DATA,
		PET_DATA,
		MIX_DATA,
		JEWELOFHARMONYOPTION_DATA,
		MASTERSKILLTREE_DATA,
		MONSTERSCRIPT_DATA,
		MONSTERSKILL_DATA,
		NPCDIALOG_DATA,
		QUEST_DATA,
		QUESTPROGRESS_DATA,
		QUESTWORDS_DATA,
		SLIDE_DATA,
	};
	extern MULoadingData Load[];
	extern const mu_uint32 LoadCount;
};

#endif