#ifndef __MU_TEXTURE_LIST_H__
#define __MU_TEXTURE_LIST_H__

#pragma once

#define MAX_RANDOM_TEXTURE 25000

enum BITMAP_ENUM : mu_uint32
{
	BITMAP_NONAMED_TEXTURES_BEGIN,
	BITMAP_NONAMED_TEXTURES_END = BITMAP_NONAMED_TEXTURES_BEGIN + MAX_RANDOM_TEXTURE - 1,

	BITMAP_BEGIN_RUNTIME,

	BITMAP_INTERFACE_MAP_BEGIN = BITMAP_BEGIN_RUNTIME,
	BITMAP_INTERFACE_MAP,
	BITMAP_INTERFACE_MAP_END = BITMAP_INTERFACE_MAP_BEGIN + 12,

	BITMAP_EXT_LOG_IN_BEGIN,
	BITMAP_EXT_LOG_IN,
	BITMAP_EXT_LOG_IN_END = BITMAP_EXT_LOG_IN_BEGIN + 10,

	BITMAP_MAPTILE_BEGIN,
	BITMAP_MAPTILE,
	BITMAP_MAPTILE_END = BITMAP_MAPTILE_BEGIN + 30,

	BITMAP_WATER_BEGIN,
	BITMAP_WATER,
	BITMAP_WATER_END = BITMAP_WATER_BEGIN + 35,

	BITMAP_RAIN_CIRCLE_BEGIN,
	BITMAP_RAIN_CIRCLE,
	BITMAP_RAIN_CIRCLE_END = BITMAP_RAIN_CIRCLE_BEGIN + 2,

	BITMAP_SKIN_BEGIN,
	BITMAP_SKIN,
	BITMAP_SKIN_END = BITMAP_SKIN_BEGIN + 20,

	BITMAP_HAIR_BEGIN,
	BITMAP_HAIR,
	BITMAP_HAIR_END = BITMAP_HAIR_BEGIN + 20,

	BITMAP_ROBE_BEGIN,
	BITMAP_ROBE,
	BITMAP_ROBE_END = BITMAP_ROBE_BEGIN + 15,

	BITMAP_HIDE,

	BITMAP_INVEN_ARMOR_BEGIN,
	BITMAP_INVEN_ARMOR,
	BITMAP_INVEN_ARMOR_END = BITMAP_INVEN_ARMOR_BEGIN + 8,

	BITMAP_INVEN_PANTS_BEGIN,
	BITMAP_INVEN_PANTS,
	BITMAP_INVEN_PANTS_END = BITMAP_INVEN_PANTS_BEGIN + 8,

	BITMAP_SHINES,
	BITMAP_RAIN,
	BITMAP_RAIN2,

	BITMAP_DARKLOAD_SKIRT_3RD,

	BITMAP_SKIN_ARMOR_DEVINE,
	BITMAP_SKIN_PANTS_DEVINE,
	BITMAP_SKIN_ARMOR_SUCCUBUS,
	BITMAP_SKIN_PANTS_SUCCUBUS,

	BITMAP_CURSEDTEMPLE_NPC_MESH_EFFECT,
	BITMAP_CURSEDTEMPLE_HOLYITEM_MESH_EFFECT,
	BITMAP_CURSEDTEMPLE_ALLIED_PHYSICSCLOTH,
	BITMAP_CURSEDTEMPLE_ILLUSION_PHYSICSCLOTH,
	BITMAP_CURSEDTEMPLE_EFFECT_MASKER,
	BITMAP_CURSEDTEMPLE_EFFECT_WIND,
	BITMAP_GHOST_CLOUD1,
	BITMAP_GHOST_CLOUD2,
	BITMAP_TORCH_FIRE,
	BITMAP_EVENT_CLOUD,

	BITMAP_LIGHT_BEGIN,
	BITMAP_LIGHT,
	BITMAP_LIGHT_END = BITMAP_LIGHT_BEGIN + 15,

	BITMAP_BLUR_BEGIN,
	BITMAP_BLUR,
	BITMAP_BLUR_END = BITMAP_BLUR_BEGIN + 20,

	BITMAP_SWORD_FORCE_BEGIN,
	BITMAP_SWORD_FORCE,
	BITMAP_SWORD_FORCE_END = BITMAP_SWORD_FORCE_BEGIN + 2,

	BITMAP_CHROME_BEGIN,
	BITMAP_CHROME,
	BITMAP_CHROME_END = BITMAP_CHROME_BEGIN + 5,

	BITMAP_SPARK_BEGIN,
	BITMAP_SPARK,
	BITMAP_SPARK_END = BITMAP_SPARK_BEGIN + 5,

	BITMAP_ENERGY_BEGIN,
	BITMAP_ENERGY,
	BITMAP_ENERGY_END = BITMAP_ENERGY_BEGIN + 10,

	BITMAP_LIGHTNING_BEGIN,
	BITMAP_LIGHTNING,
	BITMAP_LIGHTNING_END = BITMAP_LIGHTNING_BEGIN + 5,

	BITMAP_FIRE_BEGIN,
	BITMAP_FIRE,
	BITMAP_FIRE_END = BITMAP_FIRE_BEGIN + 5,

	BITMAP_FLAME_BEGIN,
	BITMAP_FLAME,
	BITMAP_FLAME_END = BITMAP_FLAME_BEGIN + 5,

	BITMAP_BLOOD_BEGIN,
	BITMAP_BLOOD,
	BITMAP_BLOOD_END = BITMAP_BLOOD_BEGIN + 5,

	BITMAP_BOSS_LASER_BEGIN,
	BITMAP_BOSS_LASER,
	BITMAP_BOSS_LASER_END = BITMAP_BOSS_LASER_BEGIN + 5,

	BITMAP_EXPLOTION_BEGIN,
	BITMAP_EXPLOTION,
	BITMAP_EXPLOTION_END = BITMAP_EXPLOTION_BEGIN + 5,

	BITMAP_SMOKE_BEGIN,
	BITMAP_SMOKE,
	BITMAP_SMOKE_END = BITMAP_SMOKE_BEGIN + 5,

	BITMAP_SHINY_BEGIN,
	BITMAP_SHINY,
	BITMAP_SHINY_END = BITMAP_SHINY_BEGIN + 7,

	BITMAP_FLOWER01_BEGIN,
	BITMAP_FLOWER01,
	BITMAP_FLOWER01_END = BITMAP_FLOWER01_BEGIN + 4,

	BITMAP_FLARE_BEGIN,
	BITMAP_FLARE,
	BITMAP_FLARE_END = BITMAP_FLARE_BEGIN + 2,

	BITMAP_JOINT_THUNDER_BEGIN,
	BITMAP_JOINT_THUNDER,
	BITMAP_JOINT_THUNDER_END = BITMAP_JOINT_THUNDER_BEGIN + 2,

	BITMAP_JOINT_LASER_BEGIN,
	BITMAP_JOINT_LASER,
	BITMAP_JOINT_LASER_END = BITMAP_JOINT_LASER_BEGIN + 2,

	BITMAP_MAGIC_BEGIN,
	BITMAP_MAGIC,
	BITMAP_MAGIC_END = BITMAP_MAGIC_BEGIN + 3,

	BITMAP_OUR_INFLUENCE_GROUND,
	BITMAP_ENEMY_INFLUENCE_GROUND,

	BITMAP_CLOUD_BEGIN,
	BITMAP_CLOUD,
	BITMAP_CLOUD_END = BITMAP_CLOUD_BEGIN + 2,

	BITMAP_BLIZZARD_BEGIN,
	BITMAP_BLIZZARD,
	BITMAP_BLIZZARD_END = BITMAP_BLIZZARD_BEGIN + 3,

	BITMAP_SPOT_WATER_BEGIN,
	BITMAP_SPOT_WATER,
	BITMAP_SPOT_WATER_END = BITMAP_SPOT_WATER_BEGIN + 15,

	BITMAP_MONSTER_SKIN_BEGIN,
	BITMAP_MONSTER_SKIN,
	BITMAP_MONSTER_SKIN_END = BITMAP_MONSTER_SKIN_BEGIN + 3,

	BITMAP_FIRECRACKER,
	BITMAP_FIRECRACKERRISE,
	BITMAP_BUBBLE,
	BITMAP_JOINT_FORCE,
	BITMAP_CHROME2,
	BITMAP_GATHERING,
	BITMAP_JOINT_SPIRIT,
	BITMAP_JOINT_FIRE,
	BITMAP_JOINT_SPARK,
	BITMAP_JOINT_ENERGY,
	BITMAP_JOINT_HEALING,
	BITMAP_JANUSEXT,
	BITMAP_SKULL,
	BITMAP_PHO_R_HAIR,
	BITMAP_PANTS_G_SOUL,
	BITMAP_FLARE_BLUE,
	BITMAP_FLARE_FORCE,
	BITMAP_FLARE_RED,
	BITMAP_WHITE_WIZARD,
	BITMAP_DEST_ORC_WAR0,
	BITMAP_DEST_ORC_WAR1,
	BITMAP_DEST_ORC_WAR2,
	BITMAP_FLASH,
	BITMAP_INFERNO,
	BITMAP_LAVA,
	BITMAP_FIRE_SNUFF,
	BITMAP_CRATER,
	BITMAP_FORMATION_MARK,
	BITMAP_PLUS,
	BITMAP_BLUR2,
	BITMAP_HGBOSS_PATTERN,
	BITMAP_HGBOSS_WING,
	BITMAP_FISSURE_FIRE,
	BITMAP_NIGHTMARE_EFFECT1,
	BITMAP_NIGHTMARE_EFFECT2,
	BITMAP_NIGHTMARE_ROBE,
	BITMAP_FENRIR_THUNDER,
	BITMAP_FENRIR_FOOT_THUNDER1,
	BITMAP_FENRIR_FOOT_THUNDER2,
	BITMAP_FENRIR_FOOT_THUNDER3,
	BITMAP_FENRIR_FOOT_THUNDER4,
	BITMAP_FENRIR_FOOT_THUNDER5,
	BITMAP_SCOLPION_TAIL,
	BITMAP_DS_EFFECT,
	BITMAP_DS_SHOCK,
	BITMAP_MAGIC_CIRCLE,
	BITMAP_CLUD64,
	BITMAP_BLUE_BLUR,
	BITMAP_ADV_SMOKE,
	BITMAP_SHOTGUN = BITMAP_ADV_SMOKE + 2,
	BITMAP_POUNDING_BALL,
	BITMAP_HOLE,
	BITMAP_CHROME3,
	BITMAP_CHROME6,
	BITMAP_CHROME7,
	BITMAP_CHROME_ENERGY,
	BITMAP_CHROME_ENERGY2,
	BITMAP_3RDWING_LAYER,
	BITMAP_CHROME8,
	BITMAP_BLUECHROME,
	BITMAP_PIERCING,
	BITMAP_MAGIC_EMBLEM,
	BITMAP_DARK_LOAD_SKIRT,
	BITMAP_SHOCK_WAVE,
	BITMAP_DAMAGE_01_MONO,
	BITMAP_SWORD_EFFECT_MONO,
	BITMAP_FLAMESTANI,
	BITMAP_TRUE_FIRE,
	BITMAP_TRUE_BLUE,
	BITMAP_JOINT_SPIRIT2,
	BITMAP_PINK_WAVE,
	BITMAP_WATERFALL_1,
	BITMAP_WATERFALL_2,
	BITMAP_WATERFALL_3,
	BITMAP_WATERFALL_4,
	BITMAP_WATERFALL_5,
	BITMAP_IMPACT,
	BITMAP_EFFECT,
	BITMAP_BERSERK_EFFECT,
	BITMAP_BERSERK_WP_EFFECT,
	BITMAP_TWINTAIL_EFFECT,
	BITMAP_PRSONA_EFFECT,
	BITMAP_PRSONA_EFFECT2,
	BITMAP_TWINTAIL_WATER,
	BITMAP_KANTURU_2ND_EFFECT1,
	BITMAP_KANTURU_2ND_NPC1,
	BITMAP_KANTURU_2ND_NPC2,
	BITMAP_KANTURU_2ND_NPC3,
	BITMAP_BLADEHUNTER_EFFECT,
	BITMAP_JACK_1,
	BITMAP_JACK_2,
	BITMAP_SNOW_EFFECT_1,
	BITMAP_SNOW_EFFECT_2,
	BITMAP_GM_HAIR_1,
	BITMAP_GM_HAIR_3,
	BITMAP_GM_AURORA,
	BITMAP_FREETICKET_R,
	BITMAP_CHAOSCARD_R,
	BITMAP_RAREITEM1_R,
	BITMAP_RAREITEM2_R,
	BITMAP_RAREITEM3_R,
	BITMAP_RAREITEM4_R,
	BITMAP_RAREITEM5_R,
	BITMAP_LUCKY_CHARM_EFFECT53,
	BITMAP_LUCKY_SEAL_EFFECT43,
	BITMAP_LUCKY_SEAL_EFFECT44,
	BITMAP_LUCKY_SEAL_EFFECT45,
	BITMAP_LUCKY_SEAL_EFFECT,
	BITMAP_CHARACTERCARD_R,
	BITMAP_NEWCHAOSCARD_GOLD_R,
	BITMAP_NEWCHAOSCARD_RARE_R,
	BITMAP_NEWCHAOSCARD_MINI_R,
	BITMAP_CHERRYBLOSSOM_EVENT_PETAL,
	BITMAP_CHERRYBLOSSOM_EVENT_FLOWER,
	BITMAP_MAYA_BODY,
	BITMAP_EXPLOTION_MONO,
	BITMAP_KANTURU3RD_OBJECT,
	BITMAP_ENERGY_RING,
	BITMAP_ENERGY_FIELD,
	BITMAP_ITEM_EFFECT_DBSTONE_R,
	BITMAP_ITEM_EFFECT_HELLHORN_R,
	BITMAP_ITEM_EFFECT_PFEATHER_R,
	BITMAP_ITEM_EFFECT_DEYE_R,
	BITMAP_ITEM_NIGHT_3RDWING_R,
	BITMAP_FIRE_RED,
	BITMAP_FIRE_CURSEDLICH,
	BITMAP_LEAF_TOTEMGOLEM,
	BITMAP_SUMMON_IMPACT,
	BITMAP_SUMMON_SAHAMUTT_EXPLOSION,
	BITMAP_ROOLOFPAPER_EFFECT_R,
	BITMAP_PIN_LIGHT,
	BITMAP_DRAIN_LIFE_GHOST,
	BITMAP_MAGIC_ZIN,
	BITMAP_ORORA,
	BITMAP_LIGHT_MARKS,
	BITMAP_TARGET_POSITION_EFFECT1,
	BITMAP_TARGET_POSITION_EFFECT2,
	BITMAP_SHADOW_PAWN_RED,
	BITMAP_SHADOW_KINGHT_BLUE,
	BITMAP_SHADOW_ROOK_GREEN,
	BITMAP_SMOKELINE1,
	BITMAP_SMOKELINE2,
	BITMAP_SMOKELINE3,
	BITMAP_LIGHTNING_MEGA1,
	BITMAP_LIGHTNING_MEGA2,
	BITMAP_LIGHTNING_MEGA3,
	BITMAP_FIRE_HIK1,
	BITMAP_FIRE_HIK3,
	BITMAP_FIRE_HIK1_MONO,
	BITMAP_FIRE_HIK2_MONO,
	BITMAP_FIRE_HIK3_MONO,

	BITMAP_SERUFAN_WAND_R,
	BITMAP_SERUFAN_ARM_R,
	BITMAP_RAKLION_CLOUDS,
	BITMAP_IRONKNIGHT_BODY_BRIGHT,
	BITMAP_SOCKETSTAFF,
	BITMAP_LIGHTMARKS,
	BITMAP_LIGHTMARKS_FOREIGN,
	BITMAP_TWLIGHT,
	BITMAP_2LINE_GHOST,
	BITMAP_FIRECRACKER0001,
	BITMAP_FIRECRACKER0002,
	BITMAP_FIRECRACKER0003,
	BITMAP_FIRECRACKER0004,
	BITMAP_FIRECRACKER0005,
	BITMAP_FIRECRACKER0006,
	BITMAP_FIRECRACKER0007,
	BITMAP_GOOD_SANTA,
	BITMAP_GOOD_SANTA_BAGGAGE,
	BITMAP_PKMON01,
	BITMAP_PKMON02,
	BITMAP_PKMON03,
	BITMAP_PKMON04,
	BITMAP_PKMON05,
	BITMAP_PKMON06,
	BITMAP_LAVAGIANT_FOOTPRINT_R,
	BITMAP_LAVAGIANT_FOOTPRINT_V,
	BITMAP_BUGBEAR_R,
	BITMAP_PANDABODY_R,
	BITMAP_DOPPELGANGER_ICEWALKER0,
	BITMAP_DOPPELGANGER_ICEWALKER1,
	BITMAP_DOPPELGANGER_SNAKE01,
	BITMAP_DOPPELGANGER_GOLDENBOX1,
	BITMAP_DOPPELGANGER_GOLDENBOX2,
	BITMAP_DEASULER_CLOTH,
	BITMAP_LIGHT_RED,
	BITMAP_GRA,
	BITMAP_RING_OF_GRADATION,
	BITMAP_RAYMOND_SWORD,
	BITMAP_ASSASSIN_EFFECT1,
	BITMAP_AG_ADDITION_EFFECT,
	BITMAP_PACKAGEBOX_BLUE,
	BITMAP_PACKAGEBOX_GOLD,
	BITMAP_PACKAGEBOX_GREEN,
	BITMAP_PACKAGEBOX_PUPLE,
	BITMAP_PACKAGEBOX_RED,
	BITMAP_PACKAGEBOX_SKY,
	BITMAP_INGAMESHOP_PRIMIUM6,
	BITMAP_INGAMESHOP_COMMUTERTICKET4,
	BITMAP_INGAMESHOP_SIZECOMMUTERTICKET3,
	BITMAP_RGB_MIX,

	BITMAP_RAREITEM7,
	BITMAP_RAREITEM8,
	BITMAP_RAREITEM9,
	BITMAP_RAREITEM10,
	BITMAP_RAREITEM11,
	BITMAP_RAREITEM12,

	BITMAP_DOPPLEGANGGER_FREETICKET,
	BITMAP_BARCA_FREETICKET,
	BITMAP_BARCA7TH_FREETICKET,

	BITMAP_ORK_CHAM_LAYER_R,
	BITMAP_MAPLE_CHAM_LAYER_R,
	BITMAP_GOLDEN_ORK_CHAM_LAYER_R,
	BITMAP_GOLDEN_MAPLE_CHAM_LAYER_R,

	// Leafs
	BITMAP_LEAF01,
	BITMAP_LEAF02,
	BITMAP_LEAF03,
	BITMAP_LEAF04,
	BITMAP_LEAF05,
	BITMAP_LEAF06,
	BITMAP_LEAF07,
	BITMAP_LEAF08,

	// Outsides
	BITMAP_OUTSIDE0,
	BITMAP_OUTSIDE1, // Map Smoke 01
	BITMAP_OUTSIDE2, // Map Smoke 02
	BITMAP_OUTSIDE3, // Map Smoke(Tarkan Sand) 01
	BITMAP_OUTSIDE4, // Map Smoke(Tarkan Sand) 02

	BITMAP_GUILD_BEGIN,
	BITMAP_GUILD_END = BITMAP_GUILD_BEGIN + MAX_MARKS - 1,
	BITMAP_GUILD2_BEGIN,
	BITMAP_GUILD2_END = BITMAP_GUILD2_BEGIN + MAX_MARKS - 1,

	MAX_TEXTURES,
};

#if (MAX_TEXTURES > 65535)
typedef mu_uint32 mu_gtype;
#else
typedef mu_uint16 mu_gtype;
#endif

namespace TEXTURES
{
	extern MULoadingData *LoadData[MAX_TEXTURES];

	extern MUTexture Data[MAX_TEXTURES];
	extern ETextureRenderProxy Proxy[MAX_TEXTURES];
	extern MULoadingData Load[];
	extern MULoadingData LoadRuntime[];
	extern const mu_uint32 LoadCount;
	extern const mu_uint32 LoadRuntimeCount;

	extern std::map<mu_string, mu_uint32> RandomTextureMap;
	extern std::map<mu_uint32, mu_string> RandomTexturePathMap;
	extern std::stack<mu_uint32> FreeRandomTexture;
	extern mu_uint32 RandomTextureIndex;
};

#endif