#include "stdafx.h"
#include "mu_texturelist.h"

namespace TEXTURES
{
	const mu_uint8 Type = MULoadingType::LOADING_TEXTURE_RUNTIME;
	const mu_uint32 Counter = LOADING_COUNTER::CT_TEXTURES;

	MULoadingData *LoadData[MAX_TEXTURES];

	MUTexture Data[MAX_TEXTURES];
	ETextureRenderProxy Proxy[MAX_TEXTURES];

	MULoadingData Load[] =
	{
		TEXTURE_LOAD(BITMAP_MAPTILE + 0, _T("./data/object25/water1.ttex"))
		TEXTURE_LOAD(BITMAP_MAPTILE + 1, _T("./data/object25/water2.jtex"))

		TEXTURE_LOAD(BITMAP_WATER + 0, _T("./data/object8/wt00.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 1, _T("./data/object8/wt01.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 2, _T("./data/object8/wt02.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 3, _T("./data/object8/wt03.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 4, _T("./data/object8/wt04.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 5, _T("./data/object8/wt05.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 6, _T("./data/object8/wt06.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 7, _T("./data/object8/wt07.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 8, _T("./data/object8/wt08.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 9, _T("./data/object8/wt09.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 10, _T("./data/object8/wt10.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 11, _T("./data/object8/wt11.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 12, _T("./data/object8/wt12.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 13, _T("./data/object8/wt13.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 14, _T("./data/object8/wt14.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 15, _T("./data/object8/wt15.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 16, _T("./data/object8/wt16.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 17, _T("./data/object8/wt17.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 18, _T("./data/object8/wt18.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 19, _T("./data/object8/wt19.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 20, _T("./data/object8/wt20.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 21, _T("./data/object8/wt21.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 22, _T("./data/object8/wt22.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 23, _T("./data/object8/wt23.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 24, _T("./data/object8/wt24.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 25, _T("./data/object8/wt25.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 26, _T("./data/object8/wt26.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 27, _T("./data/object8/wt27.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 28, _T("./data/object8/wt28.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 29, _T("./data/object8/wt29.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 30, _T("./data/object8/wt30.jtex"))
		TEXTURE_LOAD(BITMAP_WATER + 31, _T("./data/object8/wt31.jtex"))

		TEXTURE_LOAD(BITMAP_RAIN_CIRCLE + 0, _T("./data/world1/rain02.ttex"))
		TEXTURE_LOAD(BITMAP_RAIN_CIRCLE + 1, _T("./data/world10/rain03.ttex"))

		TEXTURE_LOAD(BITMAP_SKIN + 0, _T("./data/player/skin_barbarian_01.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 1, _T("./data/player/level_man022.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 2, _T("./data/player/skin_wizard_01.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 3, _T("./data/player/level_man01.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 4, _T("./data/player/skin_archer_01.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 5, _T("./data/player/level_man033.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 6, _T("./data/player/skin_special_01.jtex"))
		TEXTURE_LOAD(BITMAP_SKIN + 8, _T("./data/player/level_man02.jtex"))

		TEXTURE_LOAD(BITMAP_HAIR, _T("./data/player/hair_r.jtex"))
	};
	MULoadingData LoadRuntime[] =
	{
		DEFINE_LOAD(BITMAP_ROBE + 0, _T("./data/player/robe01.jtex"))
		DEFINE_LOAD(BITMAP_ROBE + 1, _T("./data/player/robe02.jtex"))
		DEFINE_LOAD(BITMAP_ROBE + 2, _T("./data/player/robe03.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 3, _T("./data/monster/iui02.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 5, _T("./data/monster/iui03.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 6, _T("./data/monster/iui06.jtex"))
		DEFINE_LOAD(BITMAP_ROBE + 7, _T("./data/player/darklordrobe.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 8, _T("./data/item/msword03.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 9, _T("./data/item/dl_redwings02.ttex"))
		DEFINE_LOAD(BITMAP_ROBE + 10, _T("./data/item/dl_redwings03.ttex"))

		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 0, _T("./data/player/invenarmormale40.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 1, _T("./data/player/invenarmormale41.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 2, _T("./data/player/invenarmormale42.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 3, _T("./data/player/invenarmormale43.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 4, _T("./data/player/invenarmormale44.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_ARMOR + 5, _T("./data/player/invenarmormale45.ttex"))

		DEFINE_LOAD(BITMAP_INVEN_PANTS + 0, _T("./data/player/invenpantsmale40.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_PANTS + 1, _T("./data/player/invenpantsmale41.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_PANTS + 2, _T("./data/player/invenpantsmale42.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_PANTS + 3, _T("./data/player/invenpantsmale43.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_PANTS + 4, _T("./data/player/invenpantsmale44.ttex"))
		DEFINE_LOAD(BITMAP_INVEN_PANTS + 5, _T("./data/player/invenpantsmale45.ttex"))

		DEFINE_LOAD(BITMAP_SHINES, _T("./data/object8/light01.jtex"))
		DEFINE_LOAD(BITMAP_RAIN, _T("./data/world1/rain01.ttex"))
		DEFINE_LOAD(BITMAP_RAIN2, _T("./data/world1/rain011.ttex"))

		DEFINE_LOAD(BITMAP_DARKLOAD_SKIRT_3RD, _T("./data/player/dark3chima3.ttex"))

		DEFINE_LOAD(BITMAP_SKIN_ARMOR_DEVINE, _T("./data/player/item312_armoritem.ttex"))
		DEFINE_LOAD(BITMAP_SKIN_PANTS_DEVINE, _T("./data/player/item312_pantitem.ttex"))
		DEFINE_LOAD(BITMAP_SKIN_ARMOR_SUCCUBUS, _T("./data/player/skinclass706_upperitem.ttex"))
		DEFINE_LOAD(BITMAP_SKIN_PANTS_SUCCUBUS, _T("./data/player/skinclass706_loweritem.ttex"))

		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_NPC_MESH_EFFECT, _T("./data/npc/lumi.jtex"))
		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_HOLYITEM_MESH_EFFECT, _T("./data/item/songko2_r.jtex"))
		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_ALLIED_PHYSICSCLOTH, _T("./data/skill/unitedsoldier_wing.ttex"))
		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_ILLUSION_PHYSICSCLOTH, _T("./data/skill/illusionistcloth.ttex"))
		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_EFFECT_MASKER, _T("./data/effect/masker.jtex"))
		DEFINE_LOAD(BITMAP_CURSEDTEMPLE_EFFECT_WIND, _T("./data/effect/wind01.jtex"))
		DEFINE_LOAD(BITMAP_GHOST_CLOUD1, _T("./data/effect/ghosteffect01.jtex"))
		DEFINE_LOAD(BITMAP_GHOST_CLOUD2, _T("./data/effect/ghosteffect02.jtex"))
		DEFINE_LOAD(BITMAP_TORCH_FIRE, _T("./data/effect/torchfire.jtex"))
		DEFINE_LOAD(BITMAP_EVENT_CLOUD, _T("./data/effect/clouds2.jtex"))

		DEFINE_LOAD(BITMAP_LIGHT, _T("./data/effect/flare01.jtex"))
		DEFINE_LOAD(BITMAP_LIGHT + 1, _T("./data/object9/impack03.jtex"))
		DEFINE_LOAD(BITMAP_LIGHT + 2, _T("./data/effect/cra_04.jtex"))
		DEFINE_LOAD(BITMAP_LIGHT + 3, _T("./data/effect/impack01.jtex"))

		DEFINE_LOAD(BITMAP_BLUR, _T("./data/effect/blur01.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 1, _T("./data/effect/motion_blur.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 2, _T("./data/effect/motion_blur_r.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 3, _T("./data/effect/motion_mono.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 6, _T("./data/effect/motion_blur_r3.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 7, _T("./data/effect/gra.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 8, _T("./data/effect/spinmark01.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 9, _T("./data/effect/flamestani.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 10, _T("./data/effect/sword_blur.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 11, _T("./data/effect/joint_sword_red.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 12, _T("./data/effect/motion_blur_r2.jtex"))
		DEFINE_LOAD(BITMAP_BLUR + 13, _T("./data/effect/motion_blur_r3.jtex"))

		DEFINE_LOAD(BITMAP_CHROME, _T("./data/effect/chrome01.jtex"))
		DEFINE_LOAD(BITMAP_CHROME + 1, _T("./data/effect/bab2.jtex"))

		DEFINE_LOAD(BITMAP_SPARK, _T("./data/effect/spark02.jtex"))
		DEFINE_LOAD(BITMAP_SPARK + 1, _T("./data/effect/spark03.jtex"))
		DEFINE_LOAD(BITMAP_SPARK + 2, _T("./data/effect/spark.jtex"))

		DEFINE_LOAD(BITMAP_ENERGY, _T("./data/effect/thunder01.jtex"))

		DEFINE_LOAD(BITMAP_LIGHTNING, _T("./data/effect/lightning.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTNING + 1, _T("./data/effect/lightning2.jtex"))

		DEFINE_LOAD(BITMAP_FIRE, _T("./data/effect/fire01.jtex"))
		DEFINE_LOAD(BITMAP_FIRE + 1, _T("./data/effect/fire02.jtex"))
		DEFINE_LOAD(BITMAP_FIRE + 2, _T("./data/effect/fire03.jtex"))
		DEFINE_LOAD(BITMAP_FIRE + 3, _T("./data/effect/fire05.jtex"))

		DEFINE_LOAD(BITMAP_FLAME, _T("./data/effect/flame01.jtex"))

		DEFINE_LOAD(BITMAP_BLOOD, _T("./data/effect/blood01.ttex"))
		DEFINE_LOAD(BITMAP_BLOOD + 1, _T("./data/effect/blood.ttex"))

		DEFINE_LOAD(BITMAP_EXPLOTION, _T("./data/effect/explotion01.jtex"))
		DEFINE_LOAD(BITMAP_EXPLOTION + 1, _T("./data/effect/dinoe.jtex"))

		DEFINE_LOAD(BITMAP_SMOKE, _T("./data/effect/smoke01.jtex"))
		DEFINE_LOAD(BITMAP_SMOKE + 1, _T("./data/effect/smoke02.ttex"))
		DEFINE_LOAD(BITMAP_SMOKE + 3, _T("./data/effect/smoke04.ttex"))
		DEFINE_LOAD(BITMAP_SMOKE + 4, _T("./data/effect/smoke05.ttex"))

		DEFINE_LOAD(BITMAP_SHINY, _T("./data/effect/shiny01.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 1, _T("./data/effect/shiny02.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 2, _T("./data/effect/shiny03.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 3, _T("./data/effect/eye01.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 4, _T("./data/effect/ring.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 5, _T("./data/effect/shiny04.jtex"))
		DEFINE_LOAD(BITMAP_SHINY + 6, _T("./data/effect/shiny05.jtex"))

		DEFINE_LOAD(BITMAP_FLOWER01, _T("./data/skill/flower1.ttex"))
		DEFINE_LOAD(BITMAP_FLOWER01 + 1, _T("./data/skill/flower2.ttex"))
		DEFINE_LOAD(BITMAP_FLOWER01 + 2, _T("./data/skill/flower3.ttex"))

		DEFINE_LOAD(BITMAP_FLARE, _T("./data/effect/flare.jtex"))
		DEFINE_LOAD(BITMAP_FLARE + 1, _T("./data/effect/flare02.jtex"))

		DEFINE_LOAD(BITMAP_JOINT_THUNDER, _T("./data/effect/jointthunder01.jtex"))

		DEFINE_LOAD(BITMAP_JOINT_LASER + 1, _T("./data/effect/jointlaser02.jtex"))

		DEFINE_LOAD(BITMAP_MAGIC, _T("./data/effect/magic_ground1.jtex"))
		DEFINE_LOAD(BITMAP_MAGIC + 1, _T("./data/effect/magic_ground2.jtex"))
		DEFINE_LOAD(BITMAP_MAGIC + 2, _T("./data/effect/magic_circle1.jtex"))

		DEFINE_LOAD(BITMAP_OUR_INFLUENCE_GROUND, _T("./data/effect/guild_ring01.jtex"))
		DEFINE_LOAD(BITMAP_ENEMY_INFLUENCE_GROUND, _T("./data/effect/enemy_ring02.jtex"))

		DEFINE_LOAD(BITMAP_CLOUD, _T("./data/effect/clouds.jtex"))
		DEFINE_LOAD(BITMAP_CLOUD + 1, _T("./data/effect/cloudlight.jtex"))

		DEFINE_LOAD(BITMAP_SPOT_WATER, _T("./data/effect/coll.jtex"))

		DEFINE_LOAD(BITMAP_MONSTER_SKIN, _T("./data/monster/bv01_2.jtex"))
		DEFINE_LOAD(BITMAP_MONSTER_SKIN + 1, _T("./data/monster/bv02_2.jtex"))
		DEFINE_LOAD(BITMAP_MONSTER_SKIN + 2, _T("./data/skill/dkthreebody_r.jtex"))

		DEFINE_LOAD(BITMAP_FIRECRACKER, _T("./data/effect/fire04.jtex"))
		DEFINE_LOAD(BITMAP_BUBBLE, _T("./data/object8/drop01.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_FORCE, _T("./data/effect/motion_blur_r2.jtex"))
		DEFINE_LOAD(BITMAP_CHROME2, _T("./data/effect/chrome02.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_SPIRIT, _T("./data/effect/jointspirit01.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_SPARK, _T("./data/effect/spark01.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_ENERGY, _T("./data/effect/jointlaser01.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_HEALING, _T("./data/effect/jointenergy01.jtex"))
		DEFINE_LOAD(BITMAP_JANUSEXT, _T("./data/monster/iui03.jtex"))
		DEFINE_LOAD(BITMAP_SKULL, _T("./data/skill/skull.jtex"))
		DEFINE_LOAD(BITMAP_PHO_R_HAIR, _T("./data/monster/magic_h.ttex"))
		DEFINE_LOAD(BITMAP_PANTS_G_SOUL, _T("./data/item/t_lower_14m.ttex"))
		DEFINE_LOAD(BITMAP_FLARE_BLUE, _T("./data/effect/flareblue.jtex"))
		DEFINE_LOAD(BITMAP_FLARE_FORCE, _T("./data/effect/nskill.jtex"))
		DEFINE_LOAD(BITMAP_FLARE_RED, _T("./data/effect/flarered.jtex"))
		DEFINE_LOAD(BITMAP_WHITE_WIZARD, _T("./data/monster/king11.jtex"))
		DEFINE_LOAD(BITMAP_DEST_ORC_WAR0, _T("./data/monster/kni000.jtex"))
		DEFINE_LOAD(BITMAP_DEST_ORC_WAR1, _T("./data/monster/kni011.jtex"))
		DEFINE_LOAD(BITMAP_DEST_ORC_WAR2, _T("./data/monster/kni022.jtex"))
		DEFINE_LOAD(BITMAP_FLASH, _T("./data/effect/flashing.jtex"))
		DEFINE_LOAD(BITMAP_INFERNO, _T("./data/effect/inferno.jtex"))
		DEFINE_LOAD(BITMAP_LAVA, _T("./data/effect/lava.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_SNUFF, _T("./data/effect/firesnuff.jtex"))
		DEFINE_LOAD(BITMAP_CRATER, _T("./data/effect/cratered.ttex"))
		DEFINE_LOAD(BITMAP_FORMATION_MARK, _T("./data/effect/formationmark.ttex"))
		DEFINE_LOAD(BITMAP_PLUS, _T("./data/effect/plus.ttex"))
		DEFINE_LOAD(BITMAP_BLUR2, _T("./data/effect/blur02.jtex"))
		DEFINE_LOAD(BITMAP_HGBOSS_PATTERN, _T("./data/monster/bossmap1_r.jtex"))
		DEFINE_LOAD(BITMAP_HGBOSS_WING, _T("./data/monster/bosswing.ttex"))
		DEFINE_LOAD(BITMAP_FISSURE_FIRE, _T("./data/skill/bossrock1_r.jtex"))
		DEFINE_LOAD(BITMAP_NIGHTMARE_EFFECT1, _T("./data/monster/nightmare_r.jtex"))
		DEFINE_LOAD(BITMAP_NIGHTMARE_EFFECT2, _T("./data/monster/nightmaresward_r.jtex"))
		DEFINE_LOAD(BITMAP_NIGHTMARE_ROBE, _T("./data/monster/nightmare_cloth.ttex"))
		DEFINE_LOAD(BITMAP_FENRIR_THUNDER, _T("./data/effect/eff_lighting.jtex"))
		DEFINE_LOAD(BITMAP_FENRIR_FOOT_THUNDER1, _T("./data/effect/eff_lightinga01.jtex"))
		DEFINE_LOAD(BITMAP_FENRIR_FOOT_THUNDER2, _T("./data/effect/eff_lightinga02.jtex"))
		DEFINE_LOAD(BITMAP_FENRIR_FOOT_THUNDER3, _T("./data/effect/eff_lightinga03.jtex"))
		DEFINE_LOAD(BITMAP_FENRIR_FOOT_THUNDER4, _T("./data/effect/eff_lightinga04.jtex"))
		DEFINE_LOAD(BITMAP_FENRIR_FOOT_THUNDER5, _T("./data/effect/eff_lightinga05.jtex"))
		DEFINE_LOAD(BITMAP_SCOLPION_TAIL, _T("./data/effect/scoltail.jtex"))
		DEFINE_LOAD(BITMAP_DS_EFFECT, _T("./data/effect/bowe.jtex"))
		DEFINE_LOAD(BITMAP_DS_SHOCK, _T("./data/effect/shockwave.jtex"))
		DEFINE_LOAD(BITMAP_MAGIC_CIRCLE, _T("./data/effect/mhoujin_r.jtex"))
		DEFINE_LOAD(BITMAP_CLUD64, _T("./data/effect/clud64.jtex"))
		DEFINE_LOAD(BITMAP_BLUE_BLUR, _T("./data/skill/swordeff.jtex"))
		DEFINE_LOAD(BITMAP_ADV_SMOKE, _T("./data/effect/fi01.jtex"))
		DEFINE_LOAD(BITMAP_ADV_SMOKE + 1, _T("./data/effect/fi02.ttex"))
		DEFINE_LOAD(BITMAP_POUNDING_BALL, _T("./data/effect/poundingball.jtex"))
		DEFINE_LOAD(BITMAP_HOLE, _T("./data/effect/hole.jtex"))
		DEFINE_LOAD(BITMAP_CHROME3, _T("./data/effect/chrome03.jtex"))
		DEFINE_LOAD(BITMAP_CHROME6, _T("./data/effect/chrome06.jtex"))
		DEFINE_LOAD(BITMAP_CHROME7, _T("./data/effect/chrome07.jtex"))
		DEFINE_LOAD(BITMAP_CHROME_ENERGY, _T("./data/effect/energy01.jtex"))
		DEFINE_LOAD(BITMAP_CHROME_ENERGY2, _T("./data/effect/energy02.jtex"))
		DEFINE_LOAD(BITMAP_3RDWING_LAYER, _T("./data/item/msword01_r.jtex"))
		DEFINE_LOAD(BITMAP_CHROME8, _T("./data/effect/chrome08.jtex"))
		DEFINE_LOAD(BITMAP_BLUECHROME, _T("./data/item/nfm03.jtex"))
		DEFINE_LOAD(BITMAP_PIERCING, _T("./data/effect/piercing.jtex"))
		DEFINE_LOAD(BITMAP_MAGIC_EMBLEM, _T("./data/effect/magic_b.jtex"))
		DEFINE_LOAD(BITMAP_DARK_LOAD_SKIRT, _T("./data/player/kaa.ttex"))
		DEFINE_LOAD(BITMAP_SHOCK_WAVE, _T("./data/effect/shockwave.jtex"))
		DEFINE_LOAD(BITMAP_DAMAGE_01_MONO, _T("./data/effect/damage01mono.jtex"))
		DEFINE_LOAD(BITMAP_SWORD_EFFECT_MONO, _T("./data/effect/swordeff_mono.jtex"))
		DEFINE_LOAD(BITMAP_FLAMESTANI, _T("./data/effect/flamestani.jtex"))
		DEFINE_LOAD(BITMAP_TRUE_FIRE, _T("./data/effect/fantaf.jtex"))
		DEFINE_LOAD(BITMAP_TRUE_BLUE, _T("./data/effect/fantab.jtex"))
		DEFINE_LOAD(BITMAP_JOINT_SPIRIT2, _T("./data/effect/jointspirit02.jtex"))
		DEFINE_LOAD(BITMAP_PINK_WAVE, _T("./data/skill/pinkwave.jtex"))
		DEFINE_LOAD(BITMAP_WATERFALL_1, _T("./data/effect/waterfall1.jtex"))
		DEFINE_LOAD(BITMAP_WATERFALL_2, _T("./data/effect/waterfall2.jtex"))
		DEFINE_LOAD(BITMAP_WATERFALL_3, _T("./data/effect/waterfall3.jtex"))
		DEFINE_LOAD(BITMAP_WATERFALL_4, _T("./data/effect/waterfall4.jtex"))
		DEFINE_LOAD(BITMAP_WATERFALL_5, _T("./data/effect/waterfall5.jtex"))
		DEFINE_LOAD(BITMAP_IMPACT, _T("./data/effect/impack03.jtex"))
		DEFINE_LOAD(BITMAP_EFFECT, _T("./data/logo/chasellight.jtex"))
		DEFINE_LOAD(BITMAP_BERSERK_EFFECT, _T("./data/monster/buserbody_r.jtex"))
		DEFINE_LOAD(BITMAP_BERSERK_WP_EFFECT, _T("./data/monster/busersword_r.jtex"))
		DEFINE_LOAD(BITMAP_TWINTAIL_EFFECT, _T("./data/monster/illumi_r.jtex"))
		DEFINE_LOAD(BITMAP_PRSONA_EFFECT, _T("./data/monster/prsona_r.jtex"))
		DEFINE_LOAD(BITMAP_PRSONA_EFFECT2, _T("./data/monster/prsonass_r.jtex"))
		DEFINE_LOAD(BITMAP_TWINTAIL_WATER, _T("./data/effect/water.jtex"))
		DEFINE_LOAD(BITMAP_KANTURU_2ND_EFFECT1, _T("./data/object39/k_effect_01.jtex"))
		DEFINE_LOAD(BITMAP_KANTURU_2ND_NPC1, _T("./data/npc/khs_kan2gate001.jtex"))
		DEFINE_LOAD(BITMAP_KANTURU_2ND_NPC2, _T("./data/npc/khs_kan2gate003.jtex"))
		DEFINE_LOAD(BITMAP_KANTURU_2ND_NPC3, _T("./data/npc/khs_kan2gate004.jtex"))
		DEFINE_LOAD(BITMAP_BLADEHUNTER_EFFECT, _T("./data/monster/bladeeff2_r.jtex"))
		DEFINE_LOAD(BITMAP_JACK_1, _T("./data/skill/jack04.jtex"))
		DEFINE_LOAD(BITMAP_JACK_2, _T("./data/skill/jack05.jtex"))
		DEFINE_LOAD(BITMAP_SNOW_EFFECT_1, _T("./data/effect/snowseff01.jtex"))
		DEFINE_LOAD(BITMAP_SNOW_EFFECT_2, _T("./data/effect/snowseff02.jtex"))
		DEFINE_LOAD(BITMAP_GM_HAIR_1, _T("./data/skill/younghtest1.ttex"))
		DEFINE_LOAD(BITMAP_GM_HAIR_3, _T("./data/skill/younghtest3.ttex"))
		DEFINE_LOAD(BITMAP_GM_AURORA, _T("./data/skill/gmmzine.jtex"))
		DEFINE_LOAD(BITMAP_FREETICKET_R, _T("./data/item/partcharge1/entrance_r.jtex"))
		DEFINE_LOAD(BITMAP_CHAOSCARD_R, _T("./data/item/partcharge1/juju_r.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM1_R, _T("./data/item/partcharge1/expensiveitem01_r.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM2_R, _T("./data/item/partcharge1/expensiveitem02a_r.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM3_R, _T("./data/item/partcharge1/expensiveitem02b_r.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM4_R, _T("./data/item/partcharge1/expensiveitem03a_r.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM5_R, _T("./data/item/partcharge1/expensiveitem03b_r.jtex"))
		DEFINE_LOAD(BITMAP_LUCKY_CHARM_EFFECT53, _T("./data/item/partcharge1/bujuck01alpa.jtex"))
		DEFINE_LOAD(BITMAP_LUCKY_SEAL_EFFECT43, _T("./data/item/monmark01a.jtex"))
		DEFINE_LOAD(BITMAP_LUCKY_SEAL_EFFECT44, _T("./data/item/monmark02a.jtex"))
		DEFINE_LOAD(BITMAP_LUCKY_SEAL_EFFECT45, _T("./data/item/monmark03a.jtex"))
		DEFINE_LOAD(BITMAP_LUCKY_SEAL_EFFECT, _T("./data/effect/bujuckline.jtex"))
		DEFINE_LOAD(BITMAP_CHARACTERCARD_R, _T("./data/item/partcharge3/alicecard_r.ttex"))
		DEFINE_LOAD(BITMAP_NEWCHAOSCARD_GOLD_R, _T("./data/item/partcharge3/jujug_r.jtex"))
		DEFINE_LOAD(BITMAP_NEWCHAOSCARD_RARE_R, _T("./data/item/partcharge3/jujul_r.jtex"))
		DEFINE_LOAD(BITMAP_NEWCHAOSCARD_MINI_R, _T("./data/item/partcharge3/jujum_r.jtex"))
		DEFINE_LOAD(BITMAP_CHERRYBLOSSOM_EVENT_PETAL, _T("./data/effect/cherryblossom/sakuras01.jtex"))
		DEFINE_LOAD(BITMAP_CHERRYBLOSSOM_EVENT_FLOWER, _T("./data/effect/cherryblossom/sakuras02.jtex"))
		DEFINE_LOAD(BITMAP_MAYA_BODY, _T("./data/object40/maya01_r.jtex"))
		DEFINE_LOAD(BITMAP_EXPLOTION_MONO, _T("./data/effect/explotion01mono.jtex"))
		DEFINE_LOAD(BITMAP_KANTURU3RD_OBJECT, _T("./data/object40/mtowereffe.jtex"))
		DEFINE_LOAD(BITMAP_ENERGY_RING, _T("./data/effect/bluering0001_r.jtex"))
		DEFINE_LOAD(BITMAP_ENERGY_FIELD, _T("./data/effect/bluewave0001_r.jtex"))
		DEFINE_LOAD(BITMAP_ITEM_EFFECT_DBSTONE_R, _T("./data/item/deathbeamstone_r.jtex"))
		DEFINE_LOAD(BITMAP_ITEM_EFFECT_HELLHORN_R, _T("./data/item/hellhorn_r.jtex"))
		DEFINE_LOAD(BITMAP_ITEM_EFFECT_PFEATHER_R, _T("./data/item/phoenixfeather_r.ttex"))
		DEFINE_LOAD(BITMAP_ITEM_EFFECT_DEYE_R, _T("./data/item/deye_r.jtex"))
		DEFINE_LOAD(BITMAP_ITEM_NIGHT_3RDWING_R, _T("./data/item/wing3chaking2.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_RED, _T("./data/effect/firered.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_CURSEDLICH, _T("./data/effect/firehik02.jtex"))
		DEFINE_LOAD(BITMAP_LEAF_TOTEMGOLEM, _T("./data/monster/totemgolem_leaf.ttex"))
		DEFINE_LOAD(BITMAP_SUMMON_IMPACT, _T("./data/effect/empact01.jtex"))
		DEFINE_LOAD(BITMAP_SUMMON_SAHAMUTT_EXPLOSION, _T("./data/effect/loungexflow.jtex"))
		DEFINE_LOAD(BITMAP_ROOLOFPAPER_EFFECT_R, _T("./data/item/rollofpaper_r.jtex"))
		DEFINE_LOAD(BITMAP_PIN_LIGHT, _T("./data/effect/pin_lights.jtex"))
		DEFINE_LOAD(BITMAP_DRAIN_LIFE_GHOST, _T("./data/effect/gostmark01.jtex"))
		DEFINE_LOAD(BITMAP_MAGIC_ZIN, _T("./data/effect/mzine_typer2.jtex"))
		DEFINE_LOAD(BITMAP_ORORA, _T("./data/effect/hikorora.jtex"))
		DEFINE_LOAD(BITMAP_LIGHT_MARKS, _T("./data/effect/lightmarks.jtex"))
		DEFINE_LOAD(BITMAP_TARGET_POSITION_EFFECT1, _T("./data/effect/cursorpin01.jtex"))
		DEFINE_LOAD(BITMAP_TARGET_POSITION_EFFECT2, _T("./data/effect/cursorpin02.jtex"))
		DEFINE_LOAD(BITMAP_SHADOW_PAWN_RED, _T("./data/monster/red_shadows.jtex"))
		DEFINE_LOAD(BITMAP_SHADOW_KINGHT_BLUE, _T("./data/monster/blue_shadows.jtex"))
		DEFINE_LOAD(BITMAP_SHADOW_ROOK_GREEN, _T("./data/monster/green_shadows.jtex"))
		DEFINE_LOAD(BITMAP_SMOKELINE1, _T("./data/effect/smokelines01.jtex"))
		DEFINE_LOAD(BITMAP_SMOKELINE2, _T("./data/effect/smokelines02.jtex"))
		DEFINE_LOAD(BITMAP_SMOKELINE3, _T("./data/effect/smokelines03.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTNING_MEGA1, _T("./data/effect/lighting_mega01.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTNING_MEGA2, _T("./data/effect/lighting_mega02.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTNING_MEGA3, _T("./data/effect/lighting_mega03.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_HIK1, _T("./data/effect/firehik01.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_HIK3, _T("./data/effect/firehik03.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_HIK1_MONO, _T("./data/effect/firehik_mono01.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_HIK2_MONO, _T("./data/effect/firehik_mono02.jtex"))
		DEFINE_LOAD(BITMAP_FIRE_HIK3_MONO, _T("./data/effect/firehik_mono03.jtex"))

		DEFINE_LOAD(BITMAP_SERUFAN_WAND_R, _T("./data/monster/serufanwand_r.jtex"))
		DEFINE_LOAD(BITMAP_SERUFAN_ARM_R, _T("./data/monster/serufanarm_r.jtex"))
		DEFINE_LOAD(BITMAP_RAKLION_CLOUDS, _T("./data/effect/clouds3.jtex"))
		DEFINE_LOAD(BITMAP_IRONKNIGHT_BODY_BRIGHT, _T("./data/monster/icenightlight.jtex"))
		DEFINE_LOAD(BITMAP_SOCKETSTAFF, _T("./data/item/soketmagic_stape02.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTMARKS, _T("./data/effect/lightmarks.jtex"))
		DEFINE_LOAD(BITMAP_LIGHTMARKS_FOREIGN, _T("./data/effect/lightmarks.jtex"))
		DEFINE_LOAD(BITMAP_TWLIGHT, _T("./data/skill/twlighthik01.jtex"))
		DEFINE_LOAD(BITMAP_2LINE_GHOST, _T("./data/skill/2line_gost.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0001, _T("./data/effect/firecracker0001.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0002, _T("./data/effect/firecracker0002.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0003, _T("./data/effect/firecracker0003.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0004, _T("./data/effect/firecracker0004.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0005, _T("./data/effect/firecracker0005.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0006, _T("./data/effect/firecracker0006.jtex"))
		DEFINE_LOAD(BITMAP_FIRECRACKER0007, _T("./data/effect/firecracker0007.jtex"))
		DEFINE_LOAD(BITMAP_GOOD_SANTA, _T("./data/npc/santa.jtex"))
		DEFINE_LOAD(BITMAP_GOOD_SANTA_BAGGAGE, _T("./data/npc/santa_baggage.jtex"))
		DEFINE_LOAD(BITMAP_PKMON01, _T("./data/effect/pk_mon02_fire.jtex"))
		DEFINE_LOAD(BITMAP_PKMON02, _T("./data/effect/pk_mon03_red.jtex"))
		DEFINE_LOAD(BITMAP_PKMON03, _T("./data/effect/pk_mon02_green.jtex"))
		DEFINE_LOAD(BITMAP_PKMON04, _T("./data/effect/pk_mon03_green.jtex"))
		DEFINE_LOAD(BITMAP_PKMON05, _T("./data/effect/lavagiantaa_e.jtex"))
		DEFINE_LOAD(BITMAP_PKMON06, _T("./data/effect/lavagiantba_e.jtex"))
		DEFINE_LOAD(BITMAP_LAVAGIANT_FOOTPRINT_R, _T("./data/effect/eff_magma_red.jtex"))
		DEFINE_LOAD(BITMAP_LAVAGIANT_FOOTPRINT_V, _T("./data/effect/eff_magma_violet.jtex"))
		DEFINE_LOAD(BITMAP_BUGBEAR_R, _T("./data/effect/bugbear_r.jtex"))
		DEFINE_LOAD(BITMAP_PANDABODY_R, _T("./data/item/pandabody_r.jtex"))
		DEFINE_LOAD(BITMAP_DOPPELGANGER_ICEWALKER0, _T("./data/monster/dgicewalker_body.jtex"))
		DEFINE_LOAD(BITMAP_DOPPELGANGER_ICEWALKER1, _T("./data/monster/dgicewalker_r.jtex"))
		DEFINE_LOAD(BITMAP_DOPPELGANGER_SNAKE01, _T("./data/monster/snake1.jtex"))
		DEFINE_LOAD(BITMAP_DOPPELGANGER_GOLDENBOX1, _T("./data/npc/goldboit.jtex"))
		DEFINE_LOAD(BITMAP_DOPPELGANGER_GOLDENBOX2, _T("./data/npc/goldline.jtex"))
		DEFINE_LOAD(BITMAP_DEASULER_CLOTH, _T("./data/monster/deasuler_cloth.ttex"))
		DEFINE_LOAD(BITMAP_LIGHT_RED, _T("./data/effect/flare01_red.jtex"))
		DEFINE_LOAD(BITMAP_GRA, _T("./data/effect/gra.jtex"))
		DEFINE_LOAD(BITMAP_RING_OF_GRADATION, _T("./data/effect/ring_of_gradation.jtex"))
		DEFINE_LOAD(BITMAP_RAYMOND_SWORD, _T("./data/effect/raymond_sword_r.jtex"))
		DEFINE_LOAD(BITMAP_ASSASSIN_EFFECT1, _T("./data/monster/assassinleader_body_r.jtex"))
		DEFINE_LOAD(BITMAP_AG_ADDITION_EFFECT, _T("./data/effect/mist01.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_BLUE, _T("./data/item/ingameshop/membership_item_blue.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_GOLD, _T("./data/item/ingameshop/membership_item_gold.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_GREEN, _T("./data/item/ingameshop/membership_item_green.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_PUPLE, _T("./data/item/ingameshop/membership_item_pouple.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_RED, _T("./data/item/ingameshop/membership_item_red.jtex"))
		DEFINE_LOAD(BITMAP_PACKAGEBOX_SKY, _T("./data/item/ingameshop/membership_item_sky.jtex"))
		DEFINE_LOAD(BITMAP_INGAMESHOP_PRIMIUM6, _T("./data/item/ingameshop/mebership_3items_green.jtex"))
		DEFINE_LOAD(BITMAP_INGAMESHOP_COMMUTERTICKET4, _T("./data/item/ingameshop/mebership_3items_red.jtex"))
		DEFINE_LOAD(BITMAP_INGAMESHOP_SIZECOMMUTERTICKET3, _T("./data/item/ingameshop/mebership_3items_yellow.jtex"))
		DEFINE_LOAD(BITMAP_RGB_MIX, _T("./data/item/rgb_mix.jtex"))

		DEFINE_LOAD(BITMAP_RAREITEM7, _T("./data/item/partcharge8/rareitem_ticket_7_body.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM8, _T("./data/item/partcharge8/rareitem_ticket_8_body.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM9, _T("./data/item/partcharge8/rareitem_ticket_9_body.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM10, _T("./data/item/partcharge8/rareitem_ticket_10_body.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM11, _T("./data/item/partcharge8/rareitem_ticket_11_body.jtex"))
		DEFINE_LOAD(BITMAP_RAREITEM12, _T("./data/item/partcharge8/rareitem_ticket_12_body.jtex"))

		DEFINE_LOAD(BITMAP_DOPPLEGANGGER_FREETICKET, _T("./data/item/partcharge8/doppelcard.jtex"))
		DEFINE_LOAD(BITMAP_BARCA_FREETICKET, _T("./data/item/partcharge8/barcacard.jtex"))
		DEFINE_LOAD(BITMAP_BARCA7TH_FREETICKET, _T("./data/item/partcharge8/barca7card.jtex"))

		DEFINE_LOAD(BITMAP_ORK_CHAM_LAYER_R, _T("./data/item/ork_cham_r.jtex"))
		//DEFINE_LOAD(BITMAP_MAPLE_CHAM_LAYER_R, _T("./data/item/maple_cham_r.jtex"))
		DEFINE_LOAD(BITMAP_GOLDEN_ORK_CHAM_LAYER_R, _T("./data/item/goldenork_cham_r.jtex"))
		//DEFINE_LOAD(BITMAP_GOLDEN_MAPLE_CHAM_LAYER_R, _T("./data/item/goldenmaple_cham_r.jtex"))

		DEFINE_LOAD(BITMAP_INTERFACE_MAP, _T("./data/object31/flag.ttex"))

		DEFINE_LOAD(BITMAP_EXT_LOG_IN + 2, _T("./data/effect/impack03.jtex"))

		// Leafs
		DEFINE_LOAD(BITMAP_LEAF01, _T("./data/leafs/leaf01.jtex"))
		DEFINE_LOAD(BITMAP_LEAF02, _T("./data/leafs/leaf02.jtex"))
		DEFINE_LOAD(BITMAP_LEAF03, _T("./data/leafs/leaf03.jtex"))
		DEFINE_LOAD(BITMAP_LEAF04, _T("./data/leafs/leaf04.ttex"))
		DEFINE_LOAD(BITMAP_LEAF05, _T("./data/leafs/leaf05.ttex"))
		DEFINE_LOAD(BITMAP_LEAF06, _T("./data/leafs/leaf06.ttex"))
		DEFINE_LOAD(BITMAP_LEAF07, _T("./data/leafs/leaf07.jtex"))
		DEFINE_LOAD(BITMAP_LEAF08, _T("./data/leafs/leaf08.jtex"))

		// Outsides
		DEFINE_LOAD(BITMAP_OUTSIDE0, _T("./data/effect/bab2.jtex"))
		DEFINE_LOAD(BITMAP_OUTSIDE1, _T("./data/effect/map_smoke1.jtex"))
		DEFINE_LOAD(BITMAP_OUTSIDE2, _T("./data/effect/map_smoke2.ttex"))
		DEFINE_LOAD(BITMAP_OUTSIDE3, _T("./data/object9/sand01.jtex"))
		DEFINE_LOAD(BITMAP_OUTSIDE4, _T("./data/object9/sand02.jtex"))
	};
	const mu_uint32 LoadCount = mu_countof(Load);
	const mu_uint32 LoadRuntimeCount = mu_countof(LoadRuntime);

	std::map<mu_string, mu_uint32> RandomTextureMap;
	std::map<mu_uint32, mu_string> RandomTexturePathMap;
	std::stack<mu_uint32> FreeRandomTexture;
	mu_uint32 RandomTextureIndex = BITMAP_NONAMED_TEXTURES_BEGIN;
};