#ifndef __MU_UIHELPERELFPOTIONSETTING_DEFINES_H__
#define __MU_UIHELPERELFPOTIONSETTING_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 1280.0f
#define SCREEN_HEIGHT 960.0f

#define WINBOX_WIDTH (330.0f)
#define WINBOX_HEIGHT (296.0f)
#define WINBOX_POSX (SCREEN_WIDTH * 0.5f - WINBOX_WIDTH * 0.5f)
#define WINBOX_POSY (SCREEN_HEIGHT * 0.5f - WINBOX_HEIGHT * 0.5f)

#define BUTTON_WIDTH 54.0f
#define BUTTON_HEIGHT 30.0f

#define OK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - BUTTON_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define OK_POSY (WINBOX_POSY + WINBOX_HEIGHT - BUTTON_HEIGHT - 18.0f)

#define MAIN_BACK_WIDTH (WINBOX_WIDTH - 42.0f)
#define MAIN_BACK_HEIGHT (93.0f)
#define MAIN_BACK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - MAIN_BACK_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define MAIN_BACK_POSY (WINBOX_POSY + TTEXT_MSGBOX_MOVEUP(SCREEN_HEIGHT) + 20.0f)
#define MAIN_TITLE_POSX (MAIN_BACK_POSX + MAIN_BACK_WIDTH * 0.5f)
#define MAIN_TITLE_POSY (MAIN_BACK_POSY + 25.0f)
#define MAIN_DIV_POSX (MAIN_BACK_POSX)
#define MAIN_DIV_POSY (MAIN_TITLE_POSY + 5.0f)
#define MAIN_DIV_WIDTH (MAIN_BACK_WIDTH)
#define MAIN_DIV_HEIGHT (3.0f)

#define MINLIFE_WIDTH (155.0f)
#define MINLIFE_HEIGHT (20.0f)
#define MINLIFE_POSX (MAIN_BACK_POSX + MAIN_BACK_WIDTH * 0.5f - MINLIFE_WIDTH * 0.5f)
#define MINLIFE_POSY (MAIN_DIV_POSY + (MAIN_BACK_HEIGHT - (MAIN_DIV_POSY - MAIN_BACK_POSY)) * 0.5f - MINLIFE_HEIGHT * 0.5f - 8.0f)
#define MINLIFE_LABEL_POSX (MINLIFE_POSX + MINLIFE_WIDTH + 2.0f)
#define MINLIFE_LABEL_POSY (MINLIFE_POSY + MINLIFE_HEIGHT * 0.5f)
#define MINLIFE_LABEL2_POSX (MINLIFE_POSX + MINLIFE_WIDTH * 0.5f)
#define MINLIFE_LABEL2_POSY (MINLIFE_POSY + MINLIFE_HEIGHT + 2.0f)

#define AUTOHEAL_BACK_WIDTH (WINBOX_WIDTH - 42.0f)
#define AUTOHEAL_BACK_HEIGHT (93.0f)
#define AUTOHEAL_BACK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - AUTOHEAL_BACK_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define AUTOHEAL_BACK_POSY (MAIN_BACK_POSY + MAIN_BACK_HEIGHT + 5.0f)
#define AUTOHEAL_TITLE_POSX (AUTOHEAL_BACK_POSX + AUTOHEAL_BACK_WIDTH * 0.5f)
#define AUTOHEAL_TITLE_POSY (AUTOHEAL_BACK_POSY + 25.0f)
#define AUTOHEAL_DIV_POSX (AUTOHEAL_BACK_POSX)
#define AUTOHEAL_DIV_POSY (AUTOHEAL_TITLE_POSY + 5.0f)
#define AUTOHEAL_DIV_WIDTH (AUTOHEAL_BACK_WIDTH)
#define AUTOHEAL_DIV_HEIGHT (3.0f)

#define MINAUTOHEAL_WIDTH (155.0f)
#define MINAUTOHEAL_HEIGHT (20.0f)
#define MINAUTOHEAL_POSX (AUTOHEAL_BACK_POSX + AUTOHEAL_BACK_WIDTH * 0.5f - MINAUTOHEAL_WIDTH * 0.5f)
#define MINAUTOHEAL_POSY (AUTOHEAL_DIV_POSY + (AUTOHEAL_BACK_HEIGHT - (AUTOHEAL_DIV_POSY - AUTOHEAL_BACK_POSY)) * 0.5f - MINAUTOHEAL_HEIGHT * 0.5f - 8.0f)
#define MINAUTOHEAL_LABEL_POSX (MINAUTOHEAL_POSX + MINAUTOHEAL_WIDTH + 2.0f)
#define MINAUTOHEAL_LABEL_POSY (MINAUTOHEAL_POSY + MINAUTOHEAL_HEIGHT * 0.5f)
#define MINAUTOHEAL_LABEL2_POSX (MINAUTOHEAL_POSX + MINAUTOHEAL_WIDTH * 0.5f)
#define MINAUTOHEAL_LABEL2_POSY (MINAUTOHEAL_POSY + MINAUTOHEAL_HEIGHT + 2.0f)

#endif