#ifndef __MU_UIGUILDWINDOW_DEFINES_H__
#define __MU_UIGUILDWINDOW_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 640.0f
#define SCREEN_HEIGHT 480.0f

#define BACKTEXTURE_WIDTH 225.0f
#define BACKTEXTURE_HEIGHT 512.0f

#define BACK_POSX GUILDWINDOW_POSX
#define BACK_POSY GUILDWINDOW_POSY
#define BACK_WIDTH GUILDWINDOW_WIDTH
#define BACK_HEIGHT GUILDWINDOW_HEIGHT
#define BACK_UVBEGIN EVector2(0.0f, 0.0f)
#define BACK_UVEND EVector2(BACK_WIDTH / BACKTEXTURE_WIDTH, BACK_HEIGHT / BACKTEXTURE_HEIGHT)

#define TOP_WIDTH GUILDWINDOW_WIDTH
#define TOP_HEIGHT 64.0f
#define TOP_POSX GUILDWINDOW_POSX
#define TOP_POSY GUILDWINDOW_POSY

#define BOTTOM_WIDTH GUILDWINDOW_WIDTH
#define BOTTOM_HEIGHT 45.0f
#define BOTTOM_POSX GUILDWINDOW_POSX
#define BOTTOM_POSY (GUILDWINDOW_POSY + GUILDWINDOW_HEIGHT - BOTTOM_HEIGHT)

#define LEFT_WIDTH 21.0f
#define LEFT_HEIGHT (BOTTOM_POSY - (TOP_POSY + TOP_HEIGHT))
#define LEFT_POSX GUILDWINDOW_POSX
#define LEFT_POSY (TOP_POSY + TOP_HEIGHT)

#define RIGHT_WIDTH 21.0f
#define RIGHT_HEIGHT (BOTTOM_POSY - (TOP_POSY + TOP_HEIGHT))
#define RIGHT_POSX (GUILDWINDOW_POSX + GUILDWINDOW_WIDTH - RIGHT_WIDTH)
#define RIGHT_POSY (TOP_POSY + TOP_HEIGHT)

#define XBUTTON_WIDTH 16.0f
#define XBUTTON_HEIGHT 16.0f
#define XBUTTON_POSX (TOP_POSX + TOP_WIDTH - 7.0f - XBUTTON_WIDTH)
#define XBUTTON_POSY (TOP_POSY + 7.0f)

#define TABBACK_POSX (GUILDWINDOW_POSX + 12.0f)
#define TABBACK_POSY (GUILDWINDOW_POSY + 68.0f)
#define TABBACK_WIDTH (166.0f)
#define TABBACK_HEIGHT (22.0f)

#define TABBUTTON_WIDTH (56.0f)
#define TABBUTTON_HEIGHT TABBACK_HEIGHT
#define TABBUTTON_POSX(n) (TABBACK_POSX + n * (TABBUTTON_WIDTH - 1.0f))
#define TABBUTTON_POSY TABBACK_POSY

// Guild Info
// Mark Box
#define MARKBOX_TLINE_POSX (GUILDWINDOW_POSX + 73.0f)
#define MARKBOX_TLINE_POSY (GUILDWINDOW_POSY + 104.0f)
#define MARKBOX_TLINE_WIDTH (43.0f)
#define MARKBOX_TLINE_HEIGHT (14.0f)
#define MARKBOX_BLINE_POSX (GUILDWINDOW_POSX + 73.0f)
#define MARKBOX_BLINE_POSY (GUILDWINDOW_POSY + 138.0f)
#define MARKBOX_BLINE_WIDTH (43.0f)
#define MARKBOX_BLINE_HEIGHT (14.0f)
#define MARKBOX_LLINE_POSX (GUILDWINDOW_POSX + 70.0f)
#define MARKBOX_LLINE_POSY (GUILDWINDOW_POSY + 104.0f)
#define MARKBOX_LLINE_WIDTH (14.0f)
#define MARKBOX_LLINE_HEIGHT (43.0f)
#define MARKBOX_RLINE_POSX (GUILDWINDOW_POSX + 105.0f)
#define MARKBOX_RLINE_POSY (GUILDWINDOW_POSY + 104.0f)
#define MARKBOX_RLINE_WIDTH (14.0f)
#define MARKBOX_RLINE_HEIGHT (43.0f)

#define MARKBOX_TL_POSX (GUILDWINDOW_POSX + 70.0f)
#define MARKBOX_TL_POSY (GUILDWINDOW_POSY + 104.0f)
#define MARKBOX_TL_WIDTH (14.0f)
#define MARKBOX_TL_HEIGHT (14.0f)
#define MARKBOX_TR_POSX (GUILDWINDOW_POSX + 105.0f)
#define MARKBOX_TR_POSY (GUILDWINDOW_POSY + 104.0f)
#define MARKBOX_TR_WIDTH (14.0f)
#define MARKBOX_TR_HEIGHT (14.0f)
#define MARKBOX_BL_POSX (GUILDWINDOW_POSX + 70.0f)
#define MARKBOX_BL_POSY (GUILDWINDOW_POSY + 138.0f)
#define MARKBOX_BL_WIDTH (14.0f)
#define MARKBOX_BL_HEIGHT (14.0f)
#define MARKBOX_BR_POSX (GUILDWINDOW_POSX + 105.0f)
#define MARKBOX_BR_POSY (GUILDWINDOW_POSY + 138.0f)
#define MARKBOX_BR_WIDTH (14.0f)
#define MARKBOX_BR_HEIGHT (14.0f)

#define MARKBOX_POSX (GUILDWINDOW_POSX + 74.0f)
#define MARKBOX_POSY (GUILDWINDOW_POSY + 106.0f)
#define MARKBOX_WIDTH (39.0f)
#define MARKBOX_HEIGHT (39.0f)

// Info Box
#define INFOBOX_TLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define INFOBOX_TLINE_POSY (GUILDWINDOW_POSY + 159.0f)
#define INFOBOX_TLINE_WIDTH (167.0f)
#define INFOBOX_TLINE_HEIGHT (14.0f)
#define INFOBOX_BLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define INFOBOX_BLINE_POSY (GUILDWINDOW_POSY + 215.0f)
#define INFOBOX_BLINE_WIDTH (167.0f)
#define INFOBOX_BLINE_HEIGHT (14.0f)
#define INFOBOX_LLINE_POSX (GUILDWINDOW_POSX + 10.0f)
#define INFOBOX_LLINE_POSY (GUILDWINDOW_POSY + 159.0f)
#define INFOBOX_LLINE_WIDTH (14.0f)
#define INFOBOX_LLINE_HEIGHT (66.0f)
#define INFOBOX_RLINE_POSX (GUILDWINDOW_POSX + 167.0f)
#define INFOBOX_RLINE_POSY (GUILDWINDOW_POSY + 159.0f)
#define INFOBOX_RLINE_WIDTH (14.0f)
#define INFOBOX_RLINE_HEIGHT (66.0f)

#define INFOBOX_TL_POSX (GUILDWINDOW_POSX + 10.0f)
#define INFOBOX_TL_POSY (GUILDWINDOW_POSY + 159.0f)
#define INFOBOX_TL_WIDTH (14.0f)
#define INFOBOX_TL_HEIGHT (14.0f)
#define INFOBOX_TR_POSX (GUILDWINDOW_POSX + 167.0f)
#define INFOBOX_TR_POSY (GUILDWINDOW_POSY + 159.0f)
#define INFOBOX_TR_WIDTH (14.0f)
#define INFOBOX_TR_HEIGHT (14.0f)
#define INFOBOX_BL_POSX (GUILDWINDOW_POSX + 10.0f)
#define INFOBOX_BL_POSY (GUILDWINDOW_POSY + 215.0f)
#define INFOBOX_BL_WIDTH (14.0f)
#define INFOBOX_BL_HEIGHT (14.0f)
#define INFOBOX_BR_POSX (GUILDWINDOW_POSX + 167.0f)
#define INFOBOX_BR_POSY (GUILDWINDOW_POSY + 215.0f)
#define INFOBOX_BR_WIDTH (14.0f)
#define INFOBOX_BR_HEIGHT (14.0f)

// Announcement Box
#define ANNBOX_BACK_POSX (GUILDWINDOW_POSX + 11.0f)
#define ANNBOX_BACK_POSY (GUILDWINDOW_POSY + 260.0f)
#define ANNBOX_BACK_WIDTH (165.0f)
#define ANNBOX_BACK_HEIGHT (84.0f)

#define ANNBOX_TLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define ANNBOX_TLINE_POSY (GUILDWINDOW_POSY + 260.0f)
#define ANNBOX_TLINE_WIDTH (166.0f)
#define ANNBOX_TLINE_HEIGHT (14.0f)
#define ANNBOX_BLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define ANNBOX_BLINE_POSY (GUILDWINDOW_POSY + 334.0f)
#define ANNBOX_BLINE_WIDTH (166.0f)
#define ANNBOX_BLINE_HEIGHT (14.0f)
#define ANNBOX_LLINE_POSX (GUILDWINDOW_POSX + 10.0f)
#define ANNBOX_LLINE_POSY (GUILDWINDOW_POSY + 260.0f)
#define ANNBOX_LLINE_WIDTH (14.0f)
#define ANNBOX_LLINE_HEIGHT (83.0f)
#define ANNBOX_RLINE_POSX (GUILDWINDOW_POSX + 167.0f)
#define ANNBOX_RLINE_POSY (GUILDWINDOW_POSY + 260.0f)
#define ANNBOX_RLINE_WIDTH (14.0f)
#define ANNBOX_RLINE_HEIGHT (83.0f)

#define ANNBOX_TAB_POSX (GUILDWINDOW_POSX + 11.0f)
#define ANNBOX_TAB_POSY (GUILDWINDOW_POSY + 237.0f)
#define ANNBOX_TAB_WIDTH (63.0f)
#define ANNBOX_TAB_HEIGHT (26.0f)
#define ANNBOX_TR_POSX (GUILDWINDOW_POSX + 167.0f)
#define ANNBOX_TR_POSY (GUILDWINDOW_POSY + 260.0f)
#define ANNBOX_TR_WIDTH (14.0f)
#define ANNBOX_TR_HEIGHT (14.0f)
#define ANNBOX_BL_POSX (GUILDWINDOW_POSX + 10.0f)
#define ANNBOX_BL_POSY (GUILDWINDOW_POSY + 334.0f)
#define ANNBOX_BL_WIDTH (14.0f)
#define ANNBOX_BL_HEIGHT (14.0f)
#define ANNBOX_BR_POSX (GUILDWINDOW_POSX + 167.0f)
#define ANNBOX_BR_POSY (GUILDWINDOW_POSY + 334.0f)
#define ANNBOX_BR_WIDTH (14.0f)
#define ANNBOX_BR_HEIGHT (14.0f)

#define ANNSCROLLBAR_WIDTH (7.0f)
#define ANNSCROLLBAR_BACKWIDTH (7.0f)
#define ANNSCROLLBAR_BTN_WIDTH (15.0f)
#define ANNSCROLLBAR_BTN_HEIGHT (30.0f)
#define ANNSCROLLBAR_TOP_BOTTOM_PART_HEIGHT (3.0f)
#define ANNSCROLLBAR_MIDDLE_PART_HEIGHT (14.5f)
#define ANNSCROLLBAR_BAR_WIDTH (7.0f)
#define ANNSCROLLBAR_POSX (GUILDWINDOW_POSX + 168.5f - ANNSCROLLBAR_WIDTH)
#define ANNSCROLLBAR_POSY (GUILDWINDOW_POSY + 262.0f)
#define ANNSCROLLBAR_LINESHEIGHT (5.0f * ANNSCROLLBAR_MIDDLE_PART_HEIGHT)

#define ANNTEXTBOX_POSX (GUILDWINDOW_POSX + 15.0f)
#define ANNTEXTBOX_POSY (GUILDWINDOW_POSY + 264.0f)
#define ANNTEXTBOX_WIDTH (145.0f)
#define ANNTEXTBOX_HEIGHT (70.0f)

#define BUTTON_WIDTH (64.0f)
#define BUTTON_HEIGHT (29.0f)

#define LEAVEGUILD_POSX (GUILDWINDOW_POSX + 100.0f)
#define LEAVEGUILD_POSY (GUILDWINDOW_POSY + 350.0f)

// Members Info
// List Box
#define MEMBERBOX_COLORA_POSX (GUILDWINDOW_POSX + 12.0f)
#define MEMBERBOX_COLORA_POSY (GUILDWINDOW_POSY + 125.0f)
#define MEMBERBOX_COLORA_WIDTH (165.0f)
#define MEMBERBOX_COLORA_HEIGHT (232.0f)
#define MEMBERBOX_COLORB_POSX (GUILDWINDOW_POSX + 12.0f)
#define MEMBERBOX_COLORB_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_COLORB_WIDTH (165.0f)
#define MEMBERBOX_COLORB_HEIGHT (20.0f)

#define MEMBERBOX_TLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define MEMBERBOX_TLINE_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_TLINE_WIDTH (166.0f)
#define MEMBERBOX_TLINE_HEIGHT (14.0f)
#define MEMBERBOX_BLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define MEMBERBOX_BLINE_POSY (GUILDWINDOW_POSY + 347.0f)
#define MEMBERBOX_BLINE_WIDTH (166.0f)
#define MEMBERBOX_BLINE_HEIGHT (14.0f)
#define MEMBERBOX_LLINE_POSX (GUILDWINDOW_POSX + 8.0f)
#define MEMBERBOX_LLINE_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_LLINE_WIDTH (14.0f)
#define MEMBERBOX_LLINE_HEIGHT (251.0f)
#define MEMBERBOX_RLINE_POSX (GUILDWINDOW_POSX + 168.0f)
#define MEMBERBOX_RLINE_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_RLINE_WIDTH (14.0f)
#define MEMBERBOX_RLINE_HEIGHT (251.0f)

#define MEMBERBOX_TL_POSX (GUILDWINDOW_POSX + 8.0f)
#define MEMBERBOX_TL_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_TL_WIDTH (14.0f)
#define MEMBERBOX_TL_HEIGHT (14.0f)
#define MEMBERBOX_TR_POSX (GUILDWINDOW_POSX + 168.0f)
#define MEMBERBOX_TR_POSY (GUILDWINDOW_POSY + 105.0f)
#define MEMBERBOX_TR_WIDTH (14.0f)
#define MEMBERBOX_TR_HEIGHT (14.0f)
#define MEMBERBOX_BL_POSX (GUILDWINDOW_POSX + 8.0f)
#define MEMBERBOX_BL_POSY (GUILDWINDOW_POSY + 347.0f)
#define MEMBERBOX_BL_WIDTH (14.0f)
#define MEMBERBOX_BL_HEIGHT (14.0f)
#define MEMBERBOX_BR_POSX (GUILDWINDOW_POSX + 168.0f)
#define MEMBERBOX_BR_POSY (GUILDWINDOW_POSY + 347.0f)
#define MEMBERBOX_BR_WIDTH (14.0f)
#define MEMBERBOX_BR_HEIGHT (14.0f)

#define MEMBERSCROLLBAR_WIDTH (7.0f)
#define MEMBERSCROLLBAR_BACKWIDTH (7.0f)
#define MEMBERSCROLLBAR_BTN_WIDTH (15.0f)
#define MEMBERSCROLLBAR_BTN_HEIGHT (30.0f)
#define MEMBERSCROLLBAR_TOP_BOTTOM_PART_HEIGHT (3.0f)
#define MEMBERSCROLLBAR_MIDDLE_PART_HEIGHT (14.8f)
#define MEMBERSCROLLBAR_BAR_WIDTH (7.0f)
#define MEMBERSCROLLBAR_POSX (GUILDWINDOW_POSX + 168.5f - MEMBERSCROLLBAR_WIDTH)
#define MEMBERSCROLLBAR_POSY (GUILDWINDOW_POSY + 125.5f)
#define MEMBERSCROLLBAR_LINESHEIGHT (15.0f * MEMBERSCROLLBAR_MIDDLE_PART_HEIGHT)

#define MEMBERBOX_ITEM_WIDTH (148.0f)
#define MEMBERBOX_ITEM_HEIGHT (13.0f)
#define MEMBERBOX_ITEM_POSX (GUILDWINDOW_POSX + 13.0f)
#define MEMBERBOX_ITEM_POSY(n) (GUILDWINDOW_POSY + 125.0f + (MEMBERBOX_ITEM_HEIGHT * n))

#define GETPOSITION_POSX (GUILDWINDOW_POSX + 3.0f)
#define GETPOSITION_POSY (GUILDWINDOW_POSY + 360.0f)
#define FREEPOSITION_POSX (GUILDWINDOW_POSX + 64.0f)
#define FREEPOSITION_POSY (GUILDWINDOW_POSY + 360.0f)
#define GETOUT_POSX (GUILDWINDOW_POSX + 125.0f)
#define GETOUT_POSY (GUILDWINDOW_POSY + 360.0f)

// Alliance Info
// List Box
#define ALLIANCEBOX_COLORA_POSX (GUILDWINDOW_POSX + 12.0f)
#define ALLIANCEBOX_COLORA_POSY (GUILDWINDOW_POSY + 125.0f)
#define ALLIANCEBOX_COLORA_WIDTH (165.0f)
#define ALLIANCEBOX_COLORA_HEIGHT (85.0f)
#define ALLIANCEBOX_COLORB_POSX (GUILDWINDOW_POSX + 12.0f)
#define ALLIANCEBOX_COLORB_POSY (GUILDWINDOW_POSY + 110.0f)
#define ALLIANCEBOX_COLORB_WIDTH (165.0f)
#define ALLIANCEBOX_COLORB_HEIGHT (15.0f)

#define ALLIANCEBOX_TLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define ALLIANCEBOX_TLINE_POSY (GUILDWINDOW_POSY + 109.0f)
#define ALLIANCEBOX_TLINE_WIDTH (167.0f)
#define ALLIANCEBOX_TLINE_HEIGHT (14.0f)
#define ALLIANCEBOX_BLINE_POSX (GUILDWINDOW_POSX + 12.0f)
#define ALLIANCEBOX_BLINE_POSY (GUILDWINDOW_POSY + 201.0f)
#define ALLIANCEBOX_BLINE_WIDTH (167.0f)
#define ALLIANCEBOX_BLINE_HEIGHT (14.0f)
#define ALLIANCEBOX_LLINE_POSX (GUILDWINDOW_POSX + 10.0f)
#define ALLIANCEBOX_LLINE_POSY (GUILDWINDOW_POSY + 109.0f)
#define ALLIANCEBOX_LLINE_WIDTH (14.0f)
#define ALLIANCEBOX_LLINE_HEIGHT (101.0f)
#define ALLIANCEBOX_RLINE_POSX (GUILDWINDOW_POSX + 167.0f)
#define ALLIANCEBOX_RLINE_POSY (GUILDWINDOW_POSY + 109.0f)
#define ALLIANCEBOX_RLINE_WIDTH (14.0f)
#define ALLIANCEBOX_RLINE_HEIGHT (101.0f)

#define ALLIANCEBOX_TL_POSX (GUILDWINDOW_POSX + 10.0f)
#define ALLIANCEBOX_TL_POSY (GUILDWINDOW_POSY + 109.0f)
#define ALLIANCEBOX_TL_WIDTH (14.0f)
#define ALLIANCEBOX_TL_HEIGHT (14.0f)
#define ALLIANCEBOX_TR_POSX (GUILDWINDOW_POSX + 167.0f)
#define ALLIANCEBOX_TR_POSY (GUILDWINDOW_POSY + 109.0f)
#define ALLIANCEBOX_TR_WIDTH (14.0f)
#define ALLIANCEBOX_TR_HEIGHT (14.0f)
#define ALLIANCEBOX_BL_POSX (GUILDWINDOW_POSX + 10.0f)
#define ALLIANCEBOX_BL_POSY (GUILDWINDOW_POSY + 201.0f)
#define ALLIANCEBOX_BL_WIDTH (14.0f)
#define ALLIANCEBOX_BL_HEIGHT (14.0f)
#define ALLIANCEBOX_BR_POSX (GUILDWINDOW_POSX + 167.0f)
#define ALLIANCEBOX_BR_POSY (GUILDWINDOW_POSY + 201.0f)
#define ALLIANCEBOX_BR_WIDTH (14.0f)
#define ALLIANCEBOX_BR_HEIGHT (14.0f)

#define ALLIANCESCROLLBAR_WIDTH (7.0f)
#define ALLIANCESCROLLBAR_BACKWIDTH (7.0f)
#define ALLIANCESCROLLBAR_BTN_WIDTH (15.0f)
#define ALLIANCESCROLLBAR_BTN_HEIGHT (30.0f)
#define ALLIANCESCROLLBAR_TOP_BOTTOM_PART_HEIGHT (3.0f)
#define ALLIANCESCROLLBAR_MIDDLE_PART_HEIGHT (15.0f)
#define ALLIANCESCROLLBAR_BAR_WIDTH (7.0f)
#define ALLIANCESCROLLBAR_POSX (GUILDWINDOW_POSX + 167.5f - ALLIANCESCROLLBAR_WIDTH)
#define ALLIANCESCROLLBAR_POSY (GUILDWINDOW_POSY + 125.5f)
#define ALLIANCESCROLLBAR_LINESHEIGHT (5.0f * ALLIANCESCROLLBAR_MIDDLE_PART_HEIGHT)

#define ALLIANCEBOX_ITEM_WIDTH (145.0f)
#define ALLIANCEBOX_ITEM_HEIGHT (13.0f)
#define ALLIANCEBOX_ITEM_POSX (GUILDWINDOW_POSX + 15.0f)
#define ALLIANCEBOX_ITEM_POSY(n) (GUILDWINDOW_POSY + 125.0f + (ALLIANCEBOX_ITEM_HEIGHT * n))

#define ALLIANCEBOX_MARK_WIDTH (8.0f)
#define ALLIANCEBOX_MARK_HEIGHT (8.0f)
#define ALLIANCEBOX_MARK_POSX (ALLIANCEBOX_ITEM_POSX + 2.0f)
#define ALLIANCEBOX_MARK_POSY(n) (ALLIANCEBOX_ITEM_POSY(n) + ALLIANCEBOX_ITEM_HEIGHT * 0.5f - ALLIANCEBOX_MARK_HEIGHT * 0.5f)

#define ALLIANCECREATE_POSX (GUILDWINDOW_POSX + 30.0f)
#define ALLIANCECREATE_POSY (GUILDWINDOW_POSY + 230.0f)
#define ALLIANCEOUT_POSX (GUILDWINDOW_POSX + 100.0f)
#define ALLIANCEOUT_POSY (GUILDWINDOW_POSY + 230.0f)

#endif