#ifndef __MU_UIHELPERSETUP_DEFINES_H__
#define __MU_UIHELPERSETUP_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 640.0f
#define SCREEN_HEIGHT 480.0f

#define BACKTEXTURE_WIDTH 225.0f
#define BACKTEXTURE_HEIGHT 512.0f

#define BACK_POSX HELPERSETUP_POSX
#define BACK_POSY HELPERSETUP_POSY
#define BACK_WIDTH HELPERSETUP_WIDTH
#define BACK_HEIGHT HELPERSETUP_HEIGHT
#define BACK_UVBEGIN EVector2(0.0f, 0.0f)
#define BACK_UVEND EVector2(BACK_WIDTH / BACKTEXTURE_WIDTH, BACK_HEIGHT / BACKTEXTURE_HEIGHT)

#define TOP_WIDTH HELPERSETUP_WIDTH
#define TOP_HEIGHT 64.0f
#define TOP_POSX HELPERSETUP_POSX
#define TOP_POSY HELPERSETUP_POSY

#define BOTTOM_WIDTH HELPERSETUP_WIDTH
#define BOTTOM_HEIGHT 45.0f
#define BOTTOM_POSX HELPERSETUP_POSX
#define BOTTOM_POSY (HELPERSETUP_POSY + HELPERSETUP_HEIGHT - BOTTOM_HEIGHT)

#define LEFT_WIDTH 21.0f
#define LEFT_HEIGHT (BOTTOM_POSY - (TOP_POSY + TOP_HEIGHT))
#define LEFT_POSX HELPERSETUP_POSX
#define LEFT_POSY (TOP_POSY + TOP_HEIGHT)

#define RIGHT_WIDTH 21.0f
#define RIGHT_HEIGHT (BOTTOM_POSY - (TOP_POSY + TOP_HEIGHT))
#define RIGHT_POSX (HELPERSETUP_POSX + HELPERSETUP_WIDTH - RIGHT_WIDTH)
#define RIGHT_POSY (TOP_POSY + TOP_HEIGHT)

#define XBUTTON_WIDTH 16.0f
#define XBUTTON_HEIGHT 16.0f
#define XBUTTON_POSX (TOP_POSX + TOP_WIDTH - 7.0f - XBUTTON_WIDTH)
#define XBUTTON_POSY (TOP_POSY + 7.0f)

#define COMMAND_WIDTH (108.0f)
#define COMMAND_HEIGHT (29.0f)
#define COMMAND_POSX (HELPERSETUP_POSX + HELPERSETUP_WIDTH * 0.5f - COMMAND_WIDTH * 0.5f)
#define COMMAND_POSY(n) (HELPERSETUP_POSY + 33.0f + (n * (COMMAND_HEIGHT + 1.0f)))

#define TAB_WIDTH (56.0f)
#define TAB_HEIGHT (22.0f)
#define TAB_POSX(n) (GUILDWINDOW_POSX + 12.0f + n * (TAB_WIDTH - 1.0f))
#define TAB_POSY (HELPERSETUP_POSY + 40.0f)

// Tab Frame
#define DFBACK_POSX (HELPERSETUP_POSX + 12.0f)
#define DFBACK_POSY (HELPERSETUP_POSY + TAB_POSY + TAB_HEIGHT)
#define DFBACK_WIDTH (165.0f)
#define DFBACK_HEIGHT (325.0f)
#define DFBACK_UVBEGIN EVector2(0.0f, 0.0f)
#define DFBACK_UVEND EVector2(1.0f, 1.0f)

#define DFTOP_WIDTH DFBACK_WIDTH
#define DFTOP_HEIGHT 4.0f
#define DFTOP_POSX DFBACK_POSX
#define DFTOP_POSY DFBACK_POSY

#define DFLEFT_WIDTH ((DFBACK_WIDTH / 512.0f) * 4.0f)
#define DFLEFT_HEIGHT (DFBACK_HEIGHT - DFTOP_HEIGHT * 2.0f)
#define DFLEFT_POSX DFBACK_POSX
#define DFLEFT_POSY (DFTOP_POSY + DFTOP_HEIGHT)

#define DFRIGHT_WIDTH ((DFBACK_WIDTH / 512.0f) * 4.0f)
#define DFRIGHT_HEIGHT (DFBACK_HEIGHT - DFTOP_HEIGHT * 2.0f)
#define DFRIGHT_POSX (DFBACK_POSX + DFBACK_WIDTH - DFRIGHT_WIDTH)
#define DFRIGHT_POSY (DFTOP_POSY + DFTOP_HEIGHT)

#define DFBOTTOM_WIDTH DFBACK_WIDTH
#define DFBOTTOM_HEIGHT 4.0f
#define DFBOTTOM_POSX DFBACK_POSX
#define DFBOTTOM_POSY (DFLEFT_POSY + DFLEFT_HEIGHT)

// Hunting Tab
#define HTDIV1_POSX (DFBACK_POSX + 55.0f)
#define HTDIV1_POSY (DFBACK_POSY)
#define HTDIV1_WIDTH (2.0f)
#define HTDIV1_HEIGHT (41.0f)

#define HTDIV2_POSX (DFBACK_POSX)
#define HTDIV2_POSY (HTDIV1_POSY + HTDIV1_HEIGHT)
#define HTDIV2_WIDTH (DFBACK_WIDTH)
#define HTDIV2_HEIGHT (3.0f)

#define HTRANGE_POSX (DFBACK_POSX + 10.0f)
#define HTRANGE_POSY (DFBACK_POSY + 20.0f)
#define HTRANGE_WIDTH (15.0f)
#define HTRANGE_HEIGHT (19.0f)

#define HTRANGEPLUS_POSX (DFBACK_POSX + 40.0f)
#define HTRANGEPLUS_POSY (DFBACK_POSY + 5.0f)
#define HTRANGEPLUS_WIDTH (12.0f)
#define HTRANGEPLUS_HEIGHT (11.25f)

#define HTRANGEMINUS_POSX (DFBACK_POSX + 40.0f)
#define HTRANGEMINUS_POSY (DFBACK_POSY + 5.0f + HTRANGEPLUS_HEIGHT + 3.0f)
#define HTRANGEMINUS_WIDTH (12.0f)
#define HTRANGEMINUS_HEIGHT (11.25f)

#define HTPOTION_POSX (HTDIV1_POSX + HTDIV1_WIDTH + 2.0f)
#define HTPOTION_POSY (DFBACK_POSY + 4.0f)
#define HTPOTION_WIDTH (11.25f)
#define HTPOTION_HEIGHT (11.25f)
#define HTPOTION_LABEL_POSX (HTPOTION_POSX + HTPOTION_WIDTH + 2.0f)
#define HTPOTION_LABEL_POSY (HTPOTION_POSY + HTPOTION_HEIGHT * 0.5f)

#define HTPOTION_SETTING_WIDTH (TSIZE_ROUND_WIDTH * 0.40f)
#define HTPOTION_SETTING_HEIGHT (TSIZE_ROUND_HEIGHT * 0.30f)
#define HTPOTION_SETTING_POSX (DFBACK_POSX + DFBACK_WIDTH - 2.0f - HTPOTION_SETTING_WIDTH)
#define HTPOTION_SETTING_POSY (HTPOTION_LABEL_POSY - HTPOTION_SETTING_HEIGHT * 0.5f)

#define HTAUTOHEAL_POSX (HTDIV1_POSX + HTDIV1_WIDTH + 2.0f)
#define HTAUTOHEAL_POSY (HTPOTION_POSY + HTPOTION_HEIGHT + 1.0f)
#define HTAUTOHEAL_WIDTH (11.25f)
#define HTAUTOHEAL_HEIGHT (11.25f)
#define HTAUTOHEAL_LABEL_POSX (HTAUTOHEAL_POSX + HTAUTOHEAL_WIDTH + 2.0f)
#define HTAUTOHEAL_LABEL_POSY (HTAUTOHEAL_POSY + HTAUTOHEAL_HEIGHT * 0.5f)

#define HTPARTY_POSX (HTDIV1_POSX + HTDIV1_WIDTH + 2.0f)
#define HTPARTY_POSY (HTAUTOHEAL_POSY + HTAUTOHEAL_HEIGHT + 1.0f)
#define HTPARTY_WIDTH (11.25f)
#define HTPARTY_HEIGHT (11.25f)
#define HTPARTY_LABEL_POSX (HTPARTY_POSX + HTPARTY_WIDTH + 2.0f)
#define HTPARTY_LABEL_POSY (HTPARTY_POSY + HTPARTY_HEIGHT * 0.5f)

#define HTPARTY_SETTING_WIDTH (TSIZE_ROUND_WIDTH * 0.40f)
#define HTPARTY_SETTING_HEIGHT (TSIZE_ROUND_HEIGHT * 0.30f)
#define HTPARTY_SETTING_POSX (DFBACK_POSX + DFBACK_WIDTH - 2.0f - HTPARTY_SETTING_WIDTH)
#define HTPARTY_SETTING_POSY (HTPARTY_LABEL_POSY - HTPARTY_SETTING_HEIGHT * 0.5f)

#define HTREGULARATTACK_POSX (DFBACK_POSX + 4.0f)
#define HTREGULARATTACK_POSY (HTDIV2_POSY + HTDIV2_HEIGHT + 0.5f)
#define HTREGULARATTACK_WIDTH (11.25f)
#define HTREGULARATTACK_HEIGHT (11.25f)
#define HTREGULARATTACK_LABEL_POSX (HTREGULARATTACK_POSX + HTREGULARATTACK_WIDTH + 2.0f)
#define HTREGULARATTACK_LABEL_POSY (HTREGULARATTACK_POSY + HTREGULARATTACK_HEIGHT * 0.5f)

#define HTSKILLSCLOSELY_POSX (DFBACK_POSX + 4.0f)
#define HTSKILLSCLOSELY_POSY (HTREGULARATTACK_POSY + HTREGULARATTACK_HEIGHT + 0.5f)
#define HTSKILLSCLOSELY_WIDTH (11.25f)
#define HTSKILLSCLOSELY_HEIGHT (11.25f)
#define HTSKILLSCLOSELY_LABEL_POSX (HTSKILLSCLOSELY_POSX + HTSKILLSCLOSELY_WIDTH + 2.0f)
#define HTSKILLSCLOSELY_LABEL_POSY (HTSKILLSCLOSELY_POSY + HTSKILLSCLOSELY_HEIGHT * 0.5f)

#define HTLONGDIST_POSX (DFBACK_POSX + 4.0f)
#define HTLONGDIST_POSY (HTSKILLSCLOSELY_POSY + HTSKILLSCLOSELY_HEIGHT + 0.5f)
#define HTLONGDIST_WIDTH (11.25f)
#define HTLONGDIST_HEIGHT (11.25f)
#define HTLONGDIST_LABEL_POSX (HTLONGDIST_POSX + HTLONGDIST_WIDTH + 2.0f)
#define HTLONGDIST_LABEL_POSY (HTLONGDIST_POSY + HTLONGDIST_HEIGHT * 0.5f)

#define HTORIGPOS_POSX (DFBACK_POSX + 4.0f)
#define HTORIGPOS_POSY (HTLONGDIST_POSY + HTLONGDIST_HEIGHT + 0.5f)
#define HTORIGPOS_WIDTH (11.25f)
#define HTORIGPOS_HEIGHT (11.25f)
#define HTORIGPOS_LABEL_POSX (HTORIGPOS_POSX + HTORIGPOS_WIDTH + 2.0f)
#define HTORIGPOS_LABEL_POSY (HTORIGPOS_POSY + HTORIGPOS_HEIGHT * 0.5f)

#define HTRETURNTIME_WIDTH (28.0f)
#define HTRETURNTIME_HEIGHT (15.0f)
#define HTRETURNTIME_POSX (DFBACK_POSX + 116.0f)
#define HTRETURNTIME_POSY (HTORIGPOS_LABEL_POSY - HTRETURNTIME_HEIGHT * 0.5f)
#define HTRETURNTIME_LABEL1_POSX (HTRETURNTIME_POSX - 2.0f)
#define HTRETURNTIME_LABEL1_POSY (HTRETURNTIME_POSY + HTRETURNTIME_HEIGHT * 0.5f)
#define HTRETURNTIME_LABEL2_POSX (HTRETURNTIME_POSX + HTRETURNTIME_WIDTH + 2.0f)
#define HTRETURNTIME_LABEL2_POSY (HTRETURNTIME_POSY + HTRETURNTIME_HEIGHT * 0.5f)

#define HTDIV3_POSX (DFBACK_POSX)
#define HTDIV3_POSY (HTRETURNTIME_POSY + HTRETURNTIME_HEIGHT + 1.0f)
#define HTDIV3_WIDTH (DFBACK_WIDTH)
#define HTDIV3_HEIGHT (3.0f)

#define HTBASICSKILL_POSX (DFLEFT_POSX + 5.0f)
#define HTBASICSKILL_POSY (HTDIV3_POSY + 15.0f)
#define HTBASICSKILL_WIDTH (32.0f)
#define HTBASICSKILL_HEIGHT (38.0f)
#define HTBASICSKILL_ICON_POSX (HTBASICSKILL_POSX + 6.0f)
#define HTBASICSKILL_ICON_POSY (HTBASICSKILL_POSY + 5.0f)
#define HTBASICSKILL_ICON_WIDTH (20.0f)
#define HTBASICSKILL_ICON_HEIGHT (28.0f)
#define HTBASICSKILL_LABEL_POSX (HTBASICSKILL_POSX)
#define HTBASICSKILL_LABEL_POSY (HTBASICSKILL_POSY - 2.0f)

#define HTACTSKILL1_POSX (HTBASICSKILL_POSX + HTBASICSKILL_WIDTH + 8.0f)
#define HTACTSKILL1_POSY (HTDIV3_POSY + 15.0f)
#define HTACTSKILL1_WIDTH (32.0f)
#define HTACTSKILL1_HEIGHT (38.0f)
#define HTACTSKILL1_ICON_POSX (HTACTSKILL1_POSX + 6.0f)
#define HTACTSKILL1_ICON_POSY (HTACTSKILL1_POSY + 5.0f)
#define HTACTSKILL1_ICON_WIDTH (20.0f)
#define HTACTSKILL1_ICON_HEIGHT (28.0f)
#define HTACTSKILL1_LABEL_POSX (HTACTSKILL1_POSX)
#define HTACTSKILL1_LABEL_POSY (HTACTSKILL1_POSY - 2.0f)

#define HTACTSKILL1_DELAY_POSX (HTACTSKILL1_POSX + HTACTSKILL1_WIDTH + 2.0f)
#define HTACTSKILL1_DELAY_POSY (HTACTSKILL1_POSY + 1.0f)
#define HTACTSKILL1_DELAY_WIDTH (11.25f)
#define HTACTSKILL1_DELAY_HEIGHT (11.25f)
#define HTACTSKILL1_DELAY_LABEL_POSX (HTACTSKILL1_DELAY_POSX + HTACTSKILL1_DELAY_WIDTH + 2.0f)
#define HTACTSKILL1_DELAY_LABEL_POSY (HTACTSKILL1_DELAY_POSY + HTACTSKILL1_DELAY_HEIGHT * 0.5f)

#define HTACTSKILL1_DELAYTIME_WIDTH (28.0f)
#define HTACTSKILL1_DELAYTIME_HEIGHT (15.0f)
#define HTACTSKILL1_DELAYTIME_POSX (DFBACK_POSX + 116.0f)
#define HTACTSKILL1_DELAYTIME_POSY (HTACTSKILL1_DELAY_LABEL_POSY - HTACTSKILL1_DELAYTIME_HEIGHT * 0.5f)
#define HTACTSKILL1_DELAYTIME_LABEL_POSX (HTACTSKILL1_DELAYTIME_POSX + HTACTSKILL1_DELAYTIME_WIDTH + 2.0f)
#define HTACTSKILL1_DELAYTIME_LABEL_POSY (HTACTSKILL1_DELAYTIME_POSY + HTACTSKILL1_DELAYTIME_HEIGHT * 0.5f)

#define HTACTSKILL1_CON_POSX (HTACTSKILL1_POSX + HTACTSKILL1_WIDTH + 2.0f)
#define HTACTSKILL1_CON_POSY (HTACTSKILL1_DELAY_POSY + HTACTSKILL1_DELAY_HEIGHT + 3.0f)
#define HTACTSKILL1_CON_WIDTH (11.25f)
#define HTACTSKILL1_CON_HEIGHT (11.25f)
#define HTACTSKILL1_CON_LABEL_POSX (HTACTSKILL1_CON_POSX + HTACTSKILL1_CON_WIDTH + 2.0f)
#define HTACTSKILL1_CON_LABEL_POSY (HTACTSKILL1_CON_POSY + HTACTSKILL1_CON_HEIGHT * 0.5f)

#define HTACTSKILL1_CON_SETTING_WIDTH (TSIZE_ROUND_WIDTH * 0.40f)
#define HTACTSKILL1_CON_SETTING_HEIGHT (TSIZE_ROUND_HEIGHT * 0.30f)
#define HTACTSKILL1_CON_SETTING_POSX (DFBACK_POSX + DFBACK_WIDTH - 2.0f - HTACTSKILL1_CON_SETTING_WIDTH)
#define HTACTSKILL1_CON_SETTING_POSY (HTACTSKILL1_CON_LABEL_POSY - HTACTSKILL1_CON_SETTING_HEIGHT * 0.5f)

#define HTACTSKILL2_POSX (HTBASICSKILL_POSX + HTBASICSKILL_WIDTH + 8.0f)
#define HTACTSKILL2_POSY (HTACTSKILL1_POSY + HTACTSKILL1_HEIGHT + 13.0f)
#define HTACTSKILL2_WIDTH (32.0f)
#define HTACTSKILL2_HEIGHT (38.0f)
#define HTACTSKILL2_ICON_POSX (HTACTSKILL2_POSX + 6.0f)
#define HTACTSKILL2_ICON_POSY (HTACTSKILL2_POSY + 5.0f)
#define HTACTSKILL2_ICON_WIDTH (20.0f)
#define HTACTSKILL2_ICON_HEIGHT (28.0f)
#define HTACTSKILL2_LABEL_POSX (HTACTSKILL2_POSX)
#define HTACTSKILL2_LABEL_POSY (HTACTSKILL2_POSY - 2.0f)

#define HTACTSKILL2_DELAY_POSX (HTACTSKILL2_POSX + HTACTSKILL2_WIDTH + 2.0f)
#define HTACTSKILL2_DELAY_POSY (HTACTSKILL2_POSY + 1.0f)
#define HTACTSKILL2_DELAY_WIDTH (11.25f)
#define HTACTSKILL2_DELAY_HEIGHT (11.25f)
#define HTACTSKILL2_DELAY_LABEL_POSX (HTACTSKILL2_DELAY_POSX + HTACTSKILL2_DELAY_WIDTH + 2.0f)
#define HTACTSKILL2_DELAY_LABEL_POSY (HTACTSKILL2_DELAY_POSY + HTACTSKILL2_DELAY_HEIGHT * 0.5f)

#define HTACTSKILL2_DELAYTIME_WIDTH (28.0f)
#define HTACTSKILL2_DELAYTIME_HEIGHT (15.0f)
#define HTACTSKILL2_DELAYTIME_POSX (DFBACK_POSX + 116.0f)
#define HTACTSKILL2_DELAYTIME_POSY (HTACTSKILL2_DELAY_LABEL_POSY - HTACTSKILL2_DELAYTIME_HEIGHT * 0.5f)
#define HTACTSKILL2_DELAYTIME_LABEL_POSX (HTACTSKILL2_DELAYTIME_POSX + HTACTSKILL2_DELAYTIME_WIDTH + 2.0f)
#define HTACTSKILL2_DELAYTIME_LABEL_POSY (HTACTSKILL2_DELAYTIME_POSY + HTACTSKILL2_DELAYTIME_HEIGHT * 0.5f)

#define HTACTSKILL2_CON_POSX (HTACTSKILL2_POSX + HTACTSKILL2_WIDTH + 2.0f)
#define HTACTSKILL2_CON_POSY (HTACTSKILL2_DELAY_POSY + HTACTSKILL2_DELAY_HEIGHT + 3.0f)
#define HTACTSKILL2_CON_WIDTH (11.25f)
#define HTACTSKILL2_CON_HEIGHT (11.25f)
#define HTACTSKILL2_CON_LABEL_POSX (HTACTSKILL2_CON_POSX + HTACTSKILL2_CON_WIDTH + 2.0f)
#define HTACTSKILL2_CON_LABEL_POSY (HTACTSKILL2_CON_POSY + HTACTSKILL2_CON_HEIGHT * 0.5f)

#define HTACTSKILL2_CON_SETTING_WIDTH (TSIZE_ROUND_WIDTH * 0.40f)
#define HTACTSKILL2_CON_SETTING_HEIGHT (TSIZE_ROUND_HEIGHT * 0.30f)
#define HTACTSKILL2_CON_SETTING_POSX (DFBACK_POSX + DFBACK_WIDTH - 2.0f - HTACTSKILL2_CON_SETTING_WIDTH)
#define HTACTSKILL2_CON_SETTING_POSY (HTACTSKILL2_CON_LABEL_POSY - HTACTSKILL2_CON_SETTING_HEIGHT * 0.5f)

#define HTCOMBO_POSX (DFBACK_POSX + 4.0f)
#define HTCOMBO_POSY (HTACTSKILL2_POSY)
#define HTCOMBO_WIDTH (11.25f)
#define HTCOMBO_HEIGHT (11.25f)
#define HTCOMBO_LABEL_POSX (HTCOMBO_POSX + HTCOMBO_WIDTH + 2.0f)
#define HTCOMBO_LABEL_POSY (HTCOMBO_POSY + HTCOMBO_HEIGHT * 0.5f)

#define HTDIV4_POSX (DFBACK_POSX)
#define HTDIV4_POSY (HTACTSKILL2_POSY + HTACTSKILL2_HEIGHT + 2.0f)
#define HTDIV4_WIDTH (DFBACK_WIDTH)
#define HTDIV4_HEIGHT (3.0f)

#define HTBUFFDUR_POSX (DFBACK_POSX + 4.0f)
#define HTBUFFDUR_POSY (HTDIV4_POSY + HTDIV4_HEIGHT + 0.5f)
#define HTBUFFDUR_WIDTH (11.25f)
#define HTBUFFDUR_HEIGHT (11.25f)
#define HTBUFFDUR_LABEL_POSX (HTBUFFDUR_POSX + HTBUFFDUR_WIDTH + 2.0f)
#define HTBUFFDUR_LABEL_POSY (HTBUFFDUR_POSY + HTBUFFDUR_HEIGHT * 0.5f)

#define HTBUFFSKILL1_POSX (DFBACK_POSX + 4.0f)
#define HTBUFFSKILL1_POSY (HTBUFFDUR_POSY + HTBUFFDUR_HEIGHT + 3.0f)
#define HTBUFFSKILL1_WIDTH (32.0f)
#define HTBUFFSKILL1_HEIGHT (38.0f)
#define HTBUFFSKILL1_ICON_POSX (HTBUFFSKILL1_POSX + 6.0f)
#define HTBUFFSKILL1_ICON_POSY (HTBUFFSKILL1_POSY + 5.0f)
#define HTBUFFSKILL1_ICON_WIDTH (20.0f)
#define HTBUFFSKILL1_ICON_HEIGHT (28.0f)

#define HTBUFFSKILL2_POSX (HTBUFFSKILL1_POSX + HTBUFFSKILL1_WIDTH + 2.0f)
#define HTBUFFSKILL2_POSY (HTBUFFDUR_POSY + HTBUFFDUR_HEIGHT + 3.0f)
#define HTBUFFSKILL2_WIDTH (32.0f)
#define HTBUFFSKILL2_HEIGHT (38.0f)
#define HTBUFFSKILL2_ICON_POSX (HTBUFFSKILL2_POSX + 6.0f)
#define HTBUFFSKILL2_ICON_POSY (HTBUFFSKILL2_POSY + 5.0f)
#define HTBUFFSKILL2_ICON_WIDTH (20.0f)
#define HTBUFFSKILL2_ICON_HEIGHT (28.0f)

#define HTBUFFSKILL3_POSX (HTBUFFSKILL2_POSX + HTBUFFSKILL2_WIDTH + 2.0f)
#define HTBUFFSKILL3_POSY (HTBUFFDUR_POSY + HTBUFFDUR_HEIGHT + 3.0f)
#define HTBUFFSKILL3_WIDTH (32.0f)
#define HTBUFFSKILL3_HEIGHT (38.0f)
#define HTBUFFSKILL3_ICON_POSX (HTBUFFSKILL3_POSX + 6.0f)
#define HTBUFFSKILL3_ICON_POSY (HTBUFFSKILL3_POSY + 5.0f)
#define HTBUFFSKILL3_ICON_WIDTH (20.0f)
#define HTBUFFSKILL3_ICON_HEIGHT (28.0f)

// Obtaining Tab
#define OBDIV1_POSX (DFBACK_POSX + 55.0f)
#define OBDIV1_POSY (DFBACK_POSY)
#define OBDIV1_WIDTH (2.0f)
#define OBDIV1_HEIGHT (41.0f)

#define OBDIV2_POSX (DFBACK_POSX)
#define OBDIV2_POSY (OBDIV1_POSY + OBDIV1_HEIGHT)
#define OBDIV2_WIDTH (DFBACK_WIDTH)
#define OBDIV2_HEIGHT (3.0f)

#define OBRANGE_POSX (DFBACK_POSX + 10.0f)
#define OBRANGE_POSY (DFBACK_POSY + 20.0f)
#define OBRANGE_WIDTH (15.0f)
#define OBRANGE_HEIGHT (19.0f)

#define OBRANGEPLUS_POSX (DFBACK_POSX + 40.0f)
#define OBRANGEPLUS_POSY (DFBACK_POSY + 5.0f)
#define OBRANGEPLUS_WIDTH (12.0f)
#define OBRANGEPLUS_HEIGHT (11.25f)

#define OBRANGEMINUS_POSX (DFBACK_POSX + 40.0f)
#define OBRANGEMINUS_POSY (DFBACK_POSY + 5.0f + OBRANGEPLUS_HEIGHT + 3.0f)
#define OBRANGEMINUS_WIDTH (12.0f)
#define OBRANGEMINUS_HEIGHT (11.25f)

#define OBREPAIR_POSX (OBDIV1_POSX + OBDIV1_WIDTH + 2.0f)
#define OBREPAIR_POSY (DFBACK_POSY + 4.0f)
#define OBREPAIR_WIDTH (11.25f)
#define OBREPAIR_HEIGHT (11.25f)
#define OBREPAIR_LABEL_POSX (OBREPAIR_POSX + OBREPAIR_WIDTH + 2.0f)
#define OBREPAIR_LABEL_POSY (OBREPAIR_POSY + OBREPAIR_HEIGHT * 0.5f)

#define OBPICKALL_POSX (DFBACK_POSX + 4.0f)
#define OBPICKALL_POSY (OBDIV2_POSY + OBDIV2_HEIGHT + 0.5f)
#define OBPICKALL_WIDTH (11.25f)
#define OBPICKALL_HEIGHT (11.25f)
#define OBPICKALL_LABEL_POSX (OBPICKALL_POSX + OBPICKALL_WIDTH + 2.0f)
#define OBPICKALL_LABEL_POSY (OBPICKALL_POSY + OBPICKALL_HEIGHT * 0.5f)

#define OBDIV3_POSX (DFBACK_POSX)
#define OBDIV3_POSY (OBPICKALL_POSY + OBPICKALL_HEIGHT + 2.0f)
#define OBDIV3_WIDTH (DFBACK_WIDTH)
#define OBDIV3_HEIGHT (3.0f)

#define OBPICKSEL_POSX (DFBACK_POSX + 4.0f)
#define OBPICKSEL_POSY (OBDIV3_POSY + OBDIV3_HEIGHT + 0.5f)
#define OBPICKSEL_WIDTH (11.25f)
#define OBPICKSEL_HEIGHT (11.25f)
#define OBPICKSEL_LABEL_POSX (OBPICKSEL_POSX + OBPICKSEL_WIDTH + 2.0f)
#define OBPICKSEL_LABEL_POSY (OBPICKSEL_POSY + OBPICKSEL_HEIGHT * 0.5f)

#define OBJEWEL_POSX (DFBACK_POSX + 4.0f + OBPICKSEL_WIDTH * 0.5f)
#define OBJEWEL_POSY (OBPICKSEL_POSY + OBPICKSEL_HEIGHT + 0.5f)
#define OBJEWEL_WIDTH (11.25f)
#define OBJEWEL_HEIGHT (11.25f)
#define OBJEWEL_LABEL_POSX (OBJEWEL_POSX + OBJEWEL_WIDTH + 2.0f)
#define OBJEWEL_LABEL_POSY (OBJEWEL_POSY + OBJEWEL_HEIGHT * 0.5f)

#define OBSETITEM_POSX (DFBACK_POSX + 4.0f + OBPICKSEL_WIDTH * 0.5f + 60.0f)
#define OBSETITEM_POSY (OBPICKSEL_POSY + OBPICKSEL_HEIGHT + 0.5f)
#define OBSETITEM_WIDTH (11.25f)
#define OBSETITEM_HEIGHT (11.25f)
#define OBSETITEM_LABEL_POSX (OBSETITEM_POSX + OBSETITEM_WIDTH + 2.0f)
#define OBSETITEM_LABEL_POSY (OBSETITEM_POSY + OBSETITEM_HEIGHT * 0.5f)

#define OBZEN_POSX (DFBACK_POSX + 4.0f + OBPICKSEL_WIDTH * 0.5f)
#define OBZEN_POSY (OBJEWEL_POSY + OBJEWEL_HEIGHT + 0.5f)
#define OBZEN_WIDTH (11.25f)
#define OBZEN_HEIGHT (11.25f)
#define OBZEN_LABEL_POSX (OBZEN_POSX + OBZEN_WIDTH + 2.0f)
#define OBZEN_LABEL_POSY (OBZEN_POSY + OBZEN_HEIGHT * 0.5f)

#define OBEXC_POSX (DFBACK_POSX + 4.0f + OBPICKSEL_WIDTH * 0.5f + 60.0f)
#define OBEXC_POSY (OBJEWEL_POSY + OBJEWEL_HEIGHT + 0.5f)
#define OBEXC_WIDTH (11.25f)
#define OBEXC_HEIGHT (11.25f)
#define OBEXC_LABEL_POSX (OBEXC_POSX + OBEXC_WIDTH + 2.0f)
#define OBEXC_LABEL_POSY (OBEXC_POSY + OBEXC_HEIGHT * 0.5f)

#define OBEXTRA_POSX (DFBACK_POSX + 4.0f + OBPICKSEL_WIDTH * 0.5f)
#define OBEXTRA_POSY (OBZEN_POSY + OBZEN_HEIGHT + 0.5f)
#define OBEXTRA_WIDTH (11.25f)
#define OBEXTRA_HEIGHT (11.25f)
#define OBEXTRA_LABEL_POSX (OBEXTRA_POSX + OBEXTRA_WIDTH + 2.0f)
#define OBEXTRA_LABEL_POSY (OBEXTRA_POSY + OBEXTRA_HEIGHT * 0.5f)

#define OBITEMSBOX_WIDTH (150.0f)
#define OBITEMSBOX_HEIGHT (180.0f)
#define OBITEMSBOX_POSX (DFBACK_POSX + DFBACK_WIDTH * 0.5f - OBITEMSBOX_WIDTH *0.5f)
#define OBITEMSBOX_POSY (OBEXTRA_POSY + OBEXTRA_HEIGHT + 1.0f)

#define OBITEMSCROLL_WIDTH (7.0f)
#define OBITEMSCROLL_BACKWIDTH (7.0f)
#define OBITEMSCROLL_BTN_WIDTH (15.0f)
#define OBITEMSCROLL_BTN_HEIGHT (30.0f)
#define OBITEMSCROLL_TOP_BOTTOM_PART_HEIGHT (3.0f)
#define OBITEMSCROLL_MIDDLE_PART_HEIGHT (14.8f)
#define OBITEMSCROLL_BAR_WIDTH (7.0f)
#define OBITEMSCROLL_POSX (OBITEMSBOX_POSX + OBITEMSBOX_WIDTH - 2.0f - OBITEMSCROLL_BTN_WIDTH)
#define OBITEMSCROLL_POSY (OBITEMSBOX_POSY + 5.0f)
#define OBITEMSCROLL_LINESHEIGHT (OBITEMSBOX_HEIGHT - 10.0f - OBITEMSCROLL_TOP_BOTTOM_PART_HEIGHT * 2.0f)

#define OBITEMSCROLL_START_POSX (OBITEMSBOX_POSX + 3.0f)

#define OBITEMLIST_WIDTH (OBITEMSCROLL_POSX - OBITEMSCROLL_START_POSX - 1.0f)
#define OBITEMLIST_HEIGHT (17.0f)
#define OBITEMLIST_POSX (OBITEMSCROLL_START_POSX)
#define OBITEMLIST_POSY(n) (OBITEMSBOX_POSY + 5.0f + (OBITEMLIST_HEIGHT * n))

#define OBITEMADD_WIDTH (TSIZE_ROUND_WIDTH * 0.45f)
#define OBITEMADD_HEIGHT (TSIZE_ROUND_HEIGHT * 0.35f)
#define OBITEMADD_POSX (OBITEMSBOX_POSX)
#define OBITEMADD_POSY (OBITEMSBOX_POSY + OBITEMSBOX_HEIGHT + 2.0f)

#define OBITEMMOD_WIDTH (TSIZE_ROUND_WIDTH * 0.45f)
#define OBITEMMOD_HEIGHT (TSIZE_ROUND_HEIGHT * 0.35f)
#define OBITEMMOD_POSX (OBITEMADD_POSX + OBITEMADD_WIDTH + 2.0f)
#define OBITEMMOD_POSY (OBITEMSBOX_POSY + OBITEMSBOX_HEIGHT + 2.0f)

#define OBITEMDEL_WIDTH (TSIZE_ROUND_WIDTH * 0.45f)
#define OBITEMDEL_HEIGHT (TSIZE_ROUND_HEIGHT * 0.35f)
#define OBITEMDEL_POSX (OBITEMSBOX_POSX + OBITEMSBOX_WIDTH - OBITEMDEL_WIDTH)
#define OBITEMDEL_POSY (OBITEMSBOX_POSY + OBITEMSBOX_HEIGHT + 2.0f)

#define OBDIV4_POSX (DFBACK_POSX)
#define OBDIV4_POSY (HTACTSKILL2_POSY + HTACTSKILL2_HEIGHT + 2.0f)
#define OBDIV4_WIDTH (DFBACK_WIDTH)
#define OBDIV4_HEIGHT (3.0f)

#define CLOSE_WIDTH (36.0f)
#define CLOSE_HEIGHT (29.0f)
#define CLOSE_POSX (HELPERSETUP_POSX + 13.0f)
#define CLOSE_POSY (HELPERSETUP_POSY + 391.0f)

#define RESET_WIDTH (TSIZE_ROUND_WIDTH * 0.73f)
#define RESET_HEIGHT (TSIZE_ROUND_HEIGHT * 0.63f)
#define RESET_POSX (CLOSE_POSX + CLOSE_WIDTH + 5.0f)
#define RESET_POSY (CLOSE_POSY)

#define SAVE_WIDTH (TSIZE_ROUND_WIDTH * 0.73f)
#define SAVE_HEIGHT (TSIZE_ROUND_HEIGHT * 0.63f)
#define SAVE_POSX (RESET_POSX + RESET_WIDTH + 5.0f)
#define SAVE_POSY (CLOSE_POSY)

#endif