#ifndef __MU_UIHELPERSTART_DEFINES_H__
#define __MU_UIHELPERSTART_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 1280.0f
#define SCREEN_HEIGHT 960.0f

#define WINBOX_WIDTH (180.0f)
#define WINBOX_HEIGHT (198.0f)
#define WINBOX_POSX (SCREEN_WIDTH * 0.5f - WINBOX_WIDTH * 0.5f)
#define WINBOX_POSY (SCREEN_HEIGHT * 0.5f - WINBOX_HEIGHT * 0.5f)

#define BUTTON_WIDTH (54.0f)
#define BUTTON_HEIGHT (30.0f)

#define CANCEL_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - BUTTON_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define CANCEL_POSY (WINBOX_POSY + WINBOX_HEIGHT - BUTTON_HEIGHT - 25.0f)

#define GBUTTON_WIDTH (108.0f * 1.25f)
#define GBUTTON_HEIGHT (29.0f * 1.25f)

#define ONLINE_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - GBUTTON_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define ONLINE_POSY (WINBOX_POSY + 45.0f)
#define OFFLINE_POSX (ONLINE_POSX)
#define OFFLINE_POSY (ONLINE_POSY + GBUTTON_HEIGHT + 3.0f)

#endif