#ifndef __MU_UIHELPERITEMADD_DEFINES_H__
#define __MU_UIHELPERITEMADD_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 1280.0f
#define SCREEN_HEIGHT 960.0f

#define WINBOX_WIDTH (730.0f)
#define WINBOX_HEIGHT (630.0f)
#define WINBOX_POSX (SCREEN_WIDTH * 0.5f - WINBOX_WIDTH * 0.5f)
#define WINBOX_POSY (SCREEN_HEIGHT * 0.5f - WINBOX_HEIGHT * 0.5f)

#define BUTTON_WIDTH 54.0f
#define BUTTON_HEIGHT 30.0f

#define ACCEPT_POSX (WINBOX_POSX + 120.0f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define ACCEPT_POSY (WINBOX_POSY + WINBOX_HEIGHT -  25.0f - BUTTON_HEIGHT)
#define CANCEL_POSX (WINBOX_POSX + WINBOX_WIDTH - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH) - 120.0f - BUTTON_WIDTH)
#define CANCEL_POSY (ACCEPT_POSY)

#define MAIN_BACK_WIDTH (WINBOX_WIDTH - 42.0f)
#define MAIN_BACK_HEIGHT (563.0f - TTEXT_MSGBOX_MOVEUP(SCREEN_HEIGHT) - 20.0f)
#define MAIN_BACK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - MAIN_BACK_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define MAIN_BACK_POSY (WINBOX_POSY + TTEXT_MSGBOX_MOVEUP(SCREEN_HEIGHT) + 20.0f)
#define MAIN_TITLE_POSX (MAIN_BACK_POSX + MAIN_BACK_WIDTH * 0.5f)
#define MAIN_TITLE_POSY (MAIN_BACK_POSY + 25.0f)
#define MAIN_DIV_POSX (MAIN_BACK_POSX)
#define MAIN_DIV_POSY (MAIN_TITLE_POSY + 5.0f)
#define MAIN_DIV_WIDTH (MAIN_BACK_WIDTH)
#define MAIN_DIV_HEIGHT (3.0f)

#define RENDER_DIV_POSX (MAIN_BACK_POSX + 312.0f)
#define RENDER_DIV_POSY (MAIN_DIV_POSY)
#define RENDER_DIV_WIDTH (3.0f)
#define RENDER_DIV_HEIGHT (MAIN_BACK_HEIGHT - (MAIN_DIV_POSY - MAIN_BACK_POSY))
#define RENDER_POSX (RENDER_DIV_POSX + (MAIN_BACK_WIDTH - (RENDER_DIV_POSX - MAIN_BACK_POSX)) * 0.5f)
#define RENDER_POSY (MAIN_DIV_POSY + 90.0f)
#define RENDER_NAME_POSX (RENDER_DIV_POSX + (MAIN_BACK_WIDTH - (RENDER_DIV_POSX - MAIN_BACK_POSX)) * 0.5f)
#define RENDER_NAME_POSY (RENDER_POSY + 90.0f)

#define TYPE_BACK_POSX (MAIN_BACK_POSX + 8.0f)
#define TYPE_BACK_POSY (MAIN_DIV_POSY + MAIN_DIV_HEIGHT + 2.0f)
#define TYPE_BACK_WIDTH (302.0f)
#define TYPE_BACK_HEIGHT (150.0f)

#define TYPE_SCROLL_WIDTH (10.5f)
#define TYPE_SCROLL_BACKWIDTH (10.5f)
#define TYPE_SCROLL_BTN_WIDTH (22.5f)
#define TYPE_SCROLL_BTN_HEIGHT (45.0f)
#define TYPE_SCROLL_TOP_BOTTOM_PART_HEIGHT (4.5f)
#define TYPE_SCROLL_MIDDLE_PART_HEIGHT (22.2f)
#define TYPE_SCROLL_BAR_WIDTH (10.5f)
#define TYPE_SCROLL_POSX (TYPE_BACK_POSX + TYPE_BACK_WIDTH - 4.0f - TYPE_SCROLL_BTN_WIDTH)
#define TYPE_SCROLL_POSY (TYPE_BACK_POSY + 5.0f)
#define TYPE_SCROLL_LINESHEIGHT (TYPE_BACK_HEIGHT - 10.0f - TYPE_SCROLL_TOP_BOTTOM_PART_HEIGHT * 2.0f)

#define TYPE_SCROLL_START_POSX (TYPE_BACK_POSX + 13.0f)

#define TYPE_LIST_WIDTH (TYPE_SCROLL_POSX - TYPE_SCROLL_START_POSX - 1.0f)
#define TYPE_LIST_HEIGHT (16.25f)
#define TYPE_LIST_POSX (TYPE_SCROLL_START_POSX)
#define TYPE_LIST_POSY(n) (TYPE_BACK_POSY + 10.0f + (TYPE_LIST_HEIGHT * n))

#define ITEM_BACK_POSX (TYPE_BACK_POSX)
#define ITEM_BACK_POSY (TYPE_BACK_POSY + TYPE_BACK_HEIGHT + 2.0f)
#define ITEM_BACK_WIDTH (TYPE_BACK_WIDTH)
#define ITEM_BACK_HEIGHT (150.0f)

#define ITEM_SCROLL_WIDTH (10.5f)
#define ITEM_SCROLL_BACKWIDTH (10.5f)
#define ITEM_SCROLL_BTN_WIDTH (22.5f)
#define ITEM_SCROLL_BTN_HEIGHT (45.0f)
#define ITEM_SCROLL_TOP_BOTTOM_PART_HEIGHT (4.5f)
#define ITEM_SCROLL_MIDDLE_PART_HEIGHT (22.2f)
#define ITEM_SCROLL_BAR_WIDTH (10.5f)
#define ITEM_SCROLL_POSX (ITEM_BACK_POSX + ITEM_BACK_WIDTH - 4.0f - ITEM_SCROLL_BTN_WIDTH)
#define ITEM_SCROLL_POSY (ITEM_BACK_POSY + 5.0f)
#define ITEM_SCROLL_LINESHEIGHT (ITEM_BACK_HEIGHT - 10.0f - ITEM_SCROLL_TOP_BOTTOM_PART_HEIGHT * 2.0f)

#define ITEM_SCROLL_START_POSX (ITEM_BACK_POSX + 13.0f)

#define ITEM_LIST_WIDTH (ITEM_SCROLL_POSX - ITEM_SCROLL_START_POSX - 1.0f)
#define ITEM_LIST_HEIGHT (16.25f)
#define ITEM_LIST_POSX (ITEM_SCROLL_START_POSX)
#define ITEM_LIST_POSY(n) (ITEM_BACK_POSY + 10.0f + (ITEM_LIST_HEIGHT * n))

#define DECLEVEL_WIDTH (18.75f)
#define DECLEVEL_HEIGHT (21.5625f)
#define DECLEVEL_POSX (MAIN_BACK_POSX + 6.0f)
#define DECLEVEL_POSY (ITEM_BACK_POSY + ITEM_BACK_HEIGHT + 1.0f)
#define INCLEVEL_WIDTH (18.75f)
#define INCLEVEL_HEIGHT (21.5625f)
#define INCLEVEL_POSX (DECLEVEL_POSX + DECLEVEL_WIDTH + 20.0f)
#define INCLEVEL_POSY (DECLEVEL_POSY)

#define LEVEL_POSX (DECLEVEL_POSX + DECLEVEL_WIDTH + (INCLEVEL_POSX - DECLEVEL_POSX - DECLEVEL_WIDTH) * 0.5f - 1.0f)
#define LEVEL_POSY (INCLEVEL_POSY + INCLEVEL_HEIGHT * 0.5f)
#define LEVEL_LABEL_POSX (INCLEVEL_POSX + INCLEVEL_WIDTH + 2.0f)
#define LEVEL_LABEL_POSY (LEVEL_POSY)

#define LUCK_WIDTH (22.5f)
#define LUCK_HEIGHT (22.5f)
#define LUCK_POSX (MAIN_BACK_POSX + 6.0f)
#define LUCK_POSY (DECLEVEL_POSY + DECLEVEL_HEIGHT + 1.0f)
#define LUCK_LABEL_POSX (LUCK_POSX + LUCK_WIDTH + 2.0f)
#define LUCK_LABEL_POSY (LUCK_POSY + LUCK_HEIGHT * 0.5f)

#define SKILL_WIDTH (22.5f)
#define SKILL_HEIGHT (22.5f)
#define SKILL_POSX (MAIN_BACK_POSX + 6.0f)
#define SKILL_POSY (LUCK_POSY + LUCK_HEIGHT + 1.0f)
#define SKILL_LABEL_POSX (SKILL_POSX + SKILL_WIDTH + 2.0f)
#define SKILL_LABEL_POSY (SKILL_POSY + SKILL_HEIGHT * 0.5f)

#define OPTION_WIDTH (22.5f)
#define OPTION_HEIGHT (22.5f)
#define OPTION_POSX (MAIN_BACK_POSX + 6.0f)
#define OPTION_POSY (SKILL_POSY + SKILL_HEIGHT + 1.0f)
#define OPTION_LABEL_POSX (OPTION_POSX + OPTION_WIDTH + 2.0f)
#define OPTION_LABEL_POSY (OPTION_POSY + OPTION_HEIGHT * 0.5f)

#define EXC_WIDTH (22.5f)
#define EXC_HEIGHT (22.5f)
#define EXC_POSX (MAIN_BACK_POSX + 6.0f)
#define EXC_POSY (OPTION_POSY + OPTION_HEIGHT + 1.0f)
#define EXC_LABEL_POSX (EXC_POSX + EXC_WIDTH + 2.0f)
#define EXC_LABEL_POSY (EXC_POSY + EXC_HEIGHT * 0.5f)

#define SETITEM_WIDTH (22.5f)
#define SETITEM_HEIGHT (22.5f)
#define SETITEM_POSX (MAIN_BACK_POSX + 6.0f)
#define SETITEM_POSY (EXC_POSY + EXC_HEIGHT + 1.0f)
#define SETITEM_LABEL_POSX (SETITEM_POSX + SETITEM_WIDTH + 2.0f)
#define SETITEM_LABEL_POSY (SETITEM_POSY + SETITEM_HEIGHT * 0.5f)

#define SOCKET_WIDTH (22.5f)
#define SOCKET_HEIGHT (22.5f)
#define SOCKET_POSX (MAIN_BACK_POSX + 6.0f)
#define SOCKET_POSY (SETITEM_POSY + SETITEM_HEIGHT + 1.0f)
#define SOCKET_LABEL_POSX (SOCKET_POSX + SOCKET_WIDTH + 2.0f)
#define SOCKET_LABEL_POSY (SOCKET_POSY + SOCKET_HEIGHT * 0.5f)

#endif