#ifndef __MU_UIHELPERPARTYSETTING_DEFINES_H__
#define __MU_UIHELPERPARTYSETTING_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 1280.0f
#define SCREEN_HEIGHT 960.0f

#define WINBOX_WIDTH (340.0f)
#define WINBOX_HEIGHT (316.0f)
#define WINBOX_POSX (SCREEN_WIDTH * 0.5f - WINBOX_WIDTH * 0.5f)
#define WINBOX_POSY (SCREEN_HEIGHT * 0.5f - WINBOX_HEIGHT * 0.5f)

#define BUTTON_WIDTH 54.0f
#define BUTTON_HEIGHT 30.0f

#define OK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - BUTTON_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define OK_POSY (WINBOX_POSY + WINBOX_HEIGHT - BUTTON_HEIGHT - 18.0f)

#define HEAL_BACK_WIDTH (WINBOX_WIDTH - 42.0f)
#define HEAL_BACK_HEIGHT (113.0f)
#define HEAL_BACK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - HEAL_BACK_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define HEAL_BACK_POSY (WINBOX_POSY + TTEXT_MSGBOX_MOVEUP(SCREEN_HEIGHT) + 20.0f)
#define HEAL_TITLE_POSX (HEAL_BACK_POSX + HEAL_BACK_WIDTH * 0.5f)
#define HEAL_TITLE_POSY (HEAL_BACK_POSY + 25.0f)
#define HEAL_DIV_POSX (HEAL_BACK_POSX)
#define HEAL_DIV_POSY (HEAL_TITLE_POSY + 5.0f)
#define HEAL_DIV_WIDTH (HEAL_BACK_WIDTH)
#define HEAL_DIV_HEIGHT (3.0f)

#define ENABLEHEAL_WIDTH (22.5f)
#define ENABLEHEAL_HEIGHT (22.5f)
#define ENABLEHEAL_POSX (HEAL_BACK_POSX + 6.0f)
#define ENABLEHEAL_POSY (HEAL_DIV_POSY + HEAL_DIV_HEIGHT + 1.0f)
#define ENABLEHEAL_LABEL_POSX (ENABLEHEAL_POSX + ENABLEHEAL_WIDTH + 2.0f)
#define ENABLEHEAL_LABEL_POSY (ENABLEHEAL_POSY + ENABLEHEAL_HEIGHT * 0.5f)

#define MINHEAL_WIDTH (155.0f)
#define MINHEAL_HEIGHT (20.0f)
#define MINHEAL_POSX (HEAL_BACK_POSX + HEAL_BACK_WIDTH * 0.5f - MINHEAL_WIDTH * 0.5f)
#define MINHEAL_POSY (ENABLEHEAL_POSY + ENABLEHEAL_HEIGHT + 5.0f)
#define MINHEAL_LABEL_POSX (MINHEAL_POSX + MINHEAL_WIDTH + 2.0f)
#define MINHEAL_LABEL_POSY (MINHEAL_POSY + MINHEAL_HEIGHT * 0.5f)
#define MINHEAL_LABEL2_POSX (MINHEAL_POSX + MINHEAL_WIDTH * 0.5f)
#define MINHEAL_LABEL2_POSY (MINHEAL_POSY + MINHEAL_HEIGHT + 2.0f)

#define BUFF_BACK_WIDTH (WINBOX_WIDTH - 42.0f)
#define BUFF_BACK_HEIGHT (93.0f)
#define BUFF_BACK_POSX (WINBOX_POSX + WINBOX_WIDTH * 0.5f - BUFF_BACK_WIDTH * 0.5f - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH))
#define BUFF_BACK_POSY (HEAL_BACK_POSY + HEAL_BACK_HEIGHT + 5.0f)
#define BUFF_TITLE_POSX (BUFF_BACK_POSX + BUFF_BACK_WIDTH * 0.5f)
#define BUFF_TITLE_POSY (BUFF_BACK_POSY + 25.0f)
#define BUFF_DIV_POSX (BUFF_BACK_POSX)
#define BUFF_DIV_POSY (BUFF_TITLE_POSY + 5.0f)
#define BUFF_DIV_WIDTH (BUFF_BACK_WIDTH)
#define BUFF_DIV_HEIGHT (3.0f)

#define ENABLEBUFF_WIDTH (22.5f)
#define ENABLEBUFF_HEIGHT (22.5f)
#define ENABLEBUFF_POSX (BUFF_BACK_POSX + 6.0f)
#define ENABLEBUFF_POSY (BUFF_DIV_POSY + BUFF_DIV_HEIGHT + 1.0f)
#define ENABLEBUFF_LABEL_POSX (ENABLEBUFF_POSX + ENABLEBUFF_WIDTH + 2.0f)
#define ENABLEBUFF_LABEL_POSY (ENABLEBUFF_POSY + ENABLEBUFF_HEIGHT * 0.5f)

#endif