#ifndef __MU_UIMIXCHECK_DEFINES_H__
#define __MU_UIMIXCHECK_DEFINES_H__

#pragma once

#define SCREEN_WIDTH 1280.0f
#define SCREEN_HEIGHT 960.0f

#define WINBOX_WIDTH (400.0f)
#define WINBOX_HEIGHT (250.0f)
#define WINBOX_POSX (SCREEN_WIDTH * 0.5f - WINBOX_WIDTH * 0.5f)
#define WINBOX_POSY (SCREEN_HEIGHT * 0.5f - WINBOX_HEIGHT * 0.5f)

#define BUTTON_WIDTH 54.0f
#define BUTTON_HEIGHT 30.0f

#define ACCEPT_POSX (WINBOX_POSX - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH) + 40.0f)
#define ACCEPT_POSY (WINBOX_POSY + WINBOX_HEIGHT -  TPADDING_MSGBOX_GETBOTTOM(SCREEN_HEIGHT) - 50.0f - BUTTON_HEIGHT)
#define CANCEL_POSX (WINBOX_POSX - TPADDING_MSGBOX_GETLEFT(SCREEN_WIDTH) + WINBOX_WIDTH - 40.0f - BUTTON_WIDTH)
#define CANCEL_POSY (ACCEPT_POSY)

#endif