#ifndef __MU_VULKAN_ENUM_H__
#define __MU_VULKAN_ENUM_H__

#pragma once

namespace EVulkan
{
	enum
	{
		VULKAN_POOL_FIXED,
		VULKAN_POOL_TEXTURE,
		VULKAN_POOL_FONT,
		VULKAN_POOL_MAX,
	};

	enum
	{
		VULKAN_VIEWPORT_NORMAL,
		VULKAN_VIEWPORT_LOGIN,
		VULKAN_VIEWPORT_CHARACTER,
		VULKAN_VIEWPORT_PLAYING,
		VULKAN_VIEWPORT_MAX,
	};

	enum
	{
		VULKAN_SETLAYOUT_GLOBAL_CONSTANT,
		VULKAN_SETLAYOUT_SHADOW,
		VULKAN_SETLAYOUT_BONES,

		// Terrains
		VULKAN_SETLAYOUT_TERRAIN_DATA,
		VULKAN_SETLAYOUT_TERRAIN_TEXTURE,
		VULKAN_SETLAYOUT_GRASS_TEXTURE,
		VULKAN_SETLAYOUT_WATER_TEXTURE,

		// Font
		VULKAN_SETLAYOUT_FONT_CONSTANT,
		VULKAN_SETLAYOUT_FONT_TEXTURE,

		// Textures
		VULKAN_SETLAYOUT_TEXTURE,
		VULKAN_SETLAYOUT_SAMPLER,
		
		// Effects
		VULKAN_SETLAYOUT_EFFECT_SAMPLER,

		VULKAN_SETLAYOUT_MAX,
	};

	enum
	{
		VULKAN_DESCRIPTORSET_BONES = 2,
		VULKAN_DESCRIPTORSET_UITEXTURE = 1,
		VULKAN_DESCRIPTORSET_UISAMPLER = 2,
		VULKAN_DESCRIPTORSET_TERRAINTEXTURE = 1,
		VULKAN_DESCRIPTORSET_TERRAINDATA = 3,
		VULKAN_DESCRIPTORSET_GRASSTEXTURE = 1,
		VULKAN_DESCRIPTORSET_WATERTEXTURE = 1,
		VULKAN_DESCRIPTORSET_MODELTEXTURE = 1,
		VULKAN_DESCRIPTORSET_EFFECTTEXTURE = 1,
		VULKAN_DESCRIPTORSET_EFFECTSAMPLER = 2,
		VULKAN_DESCRIPTORSET_FONTCONSTANT = 1,
		VULKAN_DESCRIPTORSET_FONTTEXTURE = 2,
		VULKAN_DESCRIPTORSET_SHADOWMAP = 2,
	};
};

#endif
