#include "stdafx.h"

#define VULKAN_DEVICE_FUNCTION(name) PFN_##name name = NULL;
#define VULKAN_GLOBAL_FUNCTION(name) PFN_##name name = NULL;
#define VULKAN_INSTANCE_FUNCTION(name) PFN_##name name = NULL;
#if !defined(NDEBUG) || defined(BACKEND_FORCE_DEBUGREPORT)
VULKAN_DEBUG_INSTANCE_FUNCTIONS()
#endif
VULKAN_GLOBAL_FUNCTIONS();
VULKAN_INSTANCE_FUNCTIONS();
VULKAN_DEVICE_FUNCTIONS();
#undef VULKAN_DEVICE_FUNCTION
#undef VULKAN_GLOBAL_FUNCTION
#undef VULKAN_INSTANCE_FUNCTION
PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = NULL;